#!/bin/bash

# Define configuration file path
source "configuration/garudrecon.cfg"
PRINTBANNER

# Check root user
AREUROOTUSER

# Help function
function show_help() {
  cat <<EOF
Usage:
  cmd/cronjobs -d <domain> -f <function>

Flags:
  -d, --domain     Domain to monitor
  -f, --function   Function to run (e.g. MONITOR_SUBDOMAIN)
  -h, --help       Show this help message

Example:
  cmd/cronjobs -d domain.com -f MONITOR_SUBDOMAIN
  cmd/cronjobs -d domain.com -f MONITOR_PORTS
  cmd/cronjobs -d domain.com -f MONITOR_ALIVESUBD
  cmd/cronjobs -d domain.com -f MONITOR_JS
  cmd/cronjobs -d domain.com -f MONITOR_JSLEAKS
EOF
}

# Parse flags
while [[ "$#" -gt 0 ]]; do
  case "$1" in
    -d|--domain)
      TARGET="$2"
      shift 2
      ;;
    -f|--function)
      FUNC="$2"
      shift 2
      ;;
    -h|--help)
      show_help
      exit 0
      ;;
    *)
      echo "Unknown flag: $1"
      exit 1
      ;;
  esac
done

# Escape dots in domain for regex
ESCAPED_TARGET=$(echo "$TARGET" | sed 's/\./\\./g')
mkdir -p "$CRONJOBS_SUBDOMAINDIR"
mkdir -p "$CRONJOBS_PORTSIR"
mkdir -p "$CRONJOBS_ALIVE_SUBDOMAINDIR"
mkdir -p "$CRONJOBS_JSDIR"
mkdir -p "$CRONJOBS_JSLEAKSDIR"

# Passive Subdomain Enumeration
MONITOR_SUBDOMAIN(){
	if [[ ! -f "${CRONJOBS_SUBDOMAINDIR}/${TARGET}.subs" ]]; then
	    curl -s "https://raw.githubusercontent.com/rix4uni/BugBountyData/refs/heads/main/data/${TARGET}.txt" | eval ${SUBDOMAIN_FILTER} | grep -aE "^(.*\.)?$ESCAPED_TARGET$" | unew -el -i -t -q ${CRONJOBS_SUBDOMAINDIR}/${TARGET}.subs
		# subfinder -duc -silent -d ${TARGET} -all -config ~/.config/subfinder/config.yaml -pc ~/.config/subfinder/provider-config.yaml -max-time ${SUBFINDER_ENUM_TIMEOUT} | eval ${SUBDOMAIN_FILTER} | grep -aE "^(.*\.)?$ESCAPED_TARGET$" | unew -el -i -t -q ${CRONJOBS_SUBDOMAINDIR}/${TARGET}.subs
		# amass enum -nocolor -nolocaldb -passive -norecursive -noalts -d ${TARGET} -config ~/.config/amass/config.ini -timeout ${AMASS_ENUM_TIMEOUT} 2>/dev/null | eval ${SUBDOMAIN_FILTER} | grep -aE "^(.*\.)?$ESCAPED_TARGET$" | unew -el -i -t -q ${CRONJOBS_SUBDOMAINDIR}/${TARGET}.subs
		# echo ${TARGET} | subdog -silent -tools all | eval ${SUBDOMAIN_FILTER} | grep -aE "^(.*\.)?$ESCAPED_TARGET$" | unew -el -i -t -q ${CRONJOBS_SUBDOMAINDIR}/${TARGET}.subs
		# echo ${TARGET} | xsubfind3r --silent | eval ${SUBDOMAIN_FILTER} | grep -aE "^(.*\.)?$ESCAPED_TARGET$" | unew -el -i -t -q ${CRONJOBS_SUBDOMAINDIR}/${TARGET}.subs
		# findomain -t ${TARGET} -q | eval ${SUBDOMAIN_FILTER} | grep -aE "^(.*\.)?$ESCAPED_TARGET$" | unew -el -i -t -q ${CRONJOBS_SUBDOMAINDIR}/${TARGET}.subs
		# chaos -duc -silent -d ${TARGET} -key $(shuf -n 1 ~/.config/chaos/chaos-api.txt) | eval ${SUBDOMAIN_FILTER} | grep -aE "^(.*\.)?$ESCAPED_TARGET$" | unew -el -i -t -q ${CRONJOBS_SUBDOMAINDIR}/${TARGET}.subs
		# cat ${CRONJOBS_SUBDOMAINDIR}/tmp-github-subdomains.subs | eval ${SUBDOMAIN_FILTER} | grep -aE "^(.*\.)?$ESCAPED_TARGET$" | unew -el -i -t -q ${CRONJOBS_SUBDOMAINDIR}/${TARGET}.subs && rm -rf ${CRONJOBS_SUBDOMAINDIR}/tmp-${TARGET}.subs
		# cat ${CRONJOBS_SUBDOMAINDIR}/bbot_scan/subdomains.txt | eval ${SUBDOMAIN_FILTER} | grep -aE "^(.*\.)?$ESCAPED_TARGET$" | unew -el -i -t -q ${CRONJOBS_SUBDOMAINDIR}/${TARGET}.subs
		# cat ${CRONJOBS_SUBDOMAINDIR}/${TARGET}-oneforall.json 2>/dev/null | jq -r '.[].subdomain' | eval ${SUBDOMAIN_FILTER} | grep -aE "^(.*\.)?$ESCAPED_TARGET$" | unew -el -i -t -q ${CRONJOBS_SUBDOMAINDIR}/${TARGET}.subs
		# shosubgo -d ${TARGET} -s $(shuf -n 1 ~/.config/shosubgo/shosubgo-api.txt) | eval ${SUBDOMAIN_FILTER} | grep -aE "^(.*\.)?$ESCAPED_TARGET$" | unew -el -i -t -q ${CRONJOBS_SUBDOMAINDIR}/${TARGET}.subs
		# assetfinder --subs-only ${TARGET} | eval ${SUBDOMAIN_FILTER} | grep -aE "^(.*\.)?$ESCAPED_TARGET$" | unew -el -i -t -q ${CRONJOBS_SUBDOMAINDIR}/${TARGET}.subs
		# echo ${TARGET} | haktrails subdomains | eval ${SUBDOMAIN_FILTER} | grep -aE "^(.*\.)?$ESCAPED_TARGET$" | unew -el -i -t -q ${CRONJOBS_SUBDOMAINDIR}/${TARGET}.subs
		# echo ${TARGET} | haktrailsfree -silent | eval ${SUBDOMAIN_FILTER} | grep -aE "^(.*\.)?$ESCAPED_TARGET$" | unew -el -i -t -q ${CRONJOBS_SUBDOMAINDIR}/${TARGET}.subs
	else
	    curl -s "https://raw.githubusercontent.com/rix4uni/BugBountyData/refs/heads/main/data/${TARGET}.txt" | eval ${SUBDOMAIN_FILTER} | grep -aE "^(.*\.)?$ESCAPED_TARGET$" | unew -el -i -t ${CRONJOBS_SUBDOMAINDIR}/${TARGET}.subs | unew -el -i -t ${CRONJOBS_SUBDOMAINDIR}/${TARGET}-new.subs | notify -silent -duc -bulk -id subdomain-moniter &>/dev/null
		# subfinder -duc -silent -d ${TARGET} -all -config ~/.config/subfinder/config.yaml -pc ~/.config/subfinder/provider-config.yaml -max-time ${SUBFINDER_ENUM_TIMEOUT} | eval ${SUBDOMAIN_FILTER} | grep -aE "^(.*\.)?$ESCAPED_TARGET$" | unew -el -i -t ${CRONJOBS_SUBDOMAINDIR}/${TARGET}.subs | unew -el -i -t ${CRONJOBS_SUBDOMAINDIR}/${TARGET}-new.subs | notify -silent -duc -bulk -id subdomain-moniter &>/dev/null
		# amass enum -nocolor -nolocaldb -passive -norecursive -noalts -d ${TARGET} -config ~/.config/amass/config.ini -timeout ${AMASS_ENUM_TIMEOUT} 2>/dev/null | eval ${SUBDOMAIN_FILTER} | grep -aE "^(.*\.)?$ESCAPED_TARGET$" | unew -el -i -t ${CRONJOBS_SUBDOMAINDIR}/${TARGET}.subs | unew -el -i -t ${CRONJOBS_SUBDOMAINDIR}/${TARGET}-new.subs | notify -silent -duc -bulk -id subdomain-moniter &>/dev/null
		# echo ${TARGET} | subdog -silent -tools all | eval ${SUBDOMAIN_FILTER} | grep -aE "^(.*\.)?$ESCAPED_TARGET$" | unew -el -i -t ${CRONJOBS_SUBDOMAINDIR}/${TARGET}.subs | unew -el -i -t ${CRONJOBS_SUBDOMAINDIR}/${TARGET}-new.subs | notify -silent -duc -bulk -id subdomain-moniter &>/dev/null
		# echo ${TARGET} | xsubfind3r --silent | eval ${SUBDOMAIN_FILTER} | grep -aE "^(.*\.)?$ESCAPED_TARGET$" | unew -el -i -t ${CRONJOBS_SUBDOMAINDIR}/${TARGET}.subs | unew -el -i -t ${CRONJOBS_SUBDOMAINDIR}/${TARGET}-new.subs | notify -silent -duc -bulk -id subdomain-moniter &>/dev/null
		# findomain -t ${TARGET} -q | eval ${SUBDOMAIN_FILTER} | grep -aE "^(.*\.)?$ESCAPED_TARGET$" | unew -el -i -t ${CRONJOBS_SUBDOMAINDIR}/${TARGET}.subs | unew -el -i -t ${CRONJOBS_SUBDOMAINDIR}/${TARGET}-new.subs | notify -silent -duc -bulk -id subdomain-moniter &>/dev/null
		# chaos -duc -silent -d ${TARGET} -key $(shuf -n 1 ~/.config/chaos/chaos-api.txt) | eval ${SUBDOMAIN_FILTER} | grep -aE "^(.*\.)?$ESCAPED_TARGET$" | unew -el -i -t ${CRONJOBS_SUBDOMAINDIR}/${TARGET}.subs | unew -el -i -t ${CRONJOBS_SUBDOMAINDIR}/${TARGET}-new.subs | notify -silent -duc -bulk -id subdomain-moniter &>/dev/null
		# cat ${CRONJOBS_SUBDOMAINDIR}/tmp-github-subdomains.subs | eval ${SUBDOMAIN_FILTER} | grep -aE "^(.*\.)?$ESCAPED_TARGET$" | unew -el -i -t ${CRONJOBS_SUBDOMAINDIR}/${TARGET}.subs && rm -rf ${CRONJOBS_SUBDOMAINDIR}/tmp-${TARGET}.subs | unew -el -i -t ${CRONJOBS_SUBDOMAINDIR}/${TARGET}-new.subs | notify -silent -duc -bulk -id subdomain-moniter &>/dev/null
		# cat ${CRONJOBS_SUBDOMAINDIR}/bbot_scan/subdomains.txt | eval ${SUBDOMAIN_FILTER} | grep -aE "^(.*\.)?$ESCAPED_TARGET$" | unew -el -i -t ${CRONJOBS_SUBDOMAINDIR}/${TARGET}.subs | unew -el -i -t ${CRONJOBS_SUBDOMAINDIR}/${TARGET}-new.subs | notify -silent -duc -bulk -id subdomain-moniter &>/dev/null
		# cat ${CRONJOBS_SUBDOMAINDIR}/${TARGET}-oneforall.json 2>/dev/null | jq -r '.[].subdomain' | eval ${SUBDOMAIN_FILTER} | grep -aE "^(.*\.)?$ESCAPED_TARGET$" | unew -el -i -t ${CRONJOBS_SUBDOMAINDIR}/${TARGET}.subs | unew -el -i -t ${CRONJOBS_SUBDOMAINDIR}/${TARGET}-new.subs | notify -silent -duc -bulk -id subdomain-moniter &>/dev/null
		# shosubgo -d ${TARGET} -s $(shuf -n 1 ~/.config/shosubgo/shosubgo-api.txt) | eval ${SUBDOMAIN_FILTER} | grep -aE "^(.*\.)?$ESCAPED_TARGET$" | unew -el -i -t ${CRONJOBS_SUBDOMAINDIR}/${TARGET}.subs | unew -el -i -t ${CRONJOBS_SUBDOMAINDIR}/${TARGET}-new.subs | notify -silent -duc -bulk -id subdomain-moniter &>/dev/null
		# assetfinder --subs-only ${TARGET} | eval ${SUBDOMAIN_FILTER} | grep -aE "^(.*\.)?$ESCAPED_TARGET$" | unew -el -i -t ${CRONJOBS_SUBDOMAINDIR}/${TARGET}.subs | unew -el -i -t ${CRONJOBS_SUBDOMAINDIR}/${TARGET}-new.subs | notify -silent -duc -bulk -id subdomain-moniter &>/dev/null
		# echo ${TARGET} | haktrails subdomains | eval ${SUBDOMAIN_FILTER} | grep -aE "^(.*\.)?$ESCAPED_TARGET$" | unew -el -i -t ${CRONJOBS_SUBDOMAINDIR}/${TARGET}.subs | unew -el -i -t ${CRONJOBS_SUBDOMAINDIR}/${TARGET}-new.subs | notify -silent -duc -bulk -id subdomain-moniter &>/dev/null
		# echo ${TARGET} | haktrailsfree -silent | eval ${SUBDOMAIN_FILTER} | grep -aE "^(.*\.)?$ESCAPED_TARGET$" | unew -el -i -t ${CRONJOBS_SUBDOMAINDIR}/${TARGET}.subs | unew -el -i -t ${CRONJOBS_SUBDOMAINDIR}/${TARGET}-new.subs | notify -silent -duc -bulk -id subdomain-moniter &>/dev/null
	fi
}


# Port Scanning
MONITOR_PORTS(){
	if [[ ! -f "${CRONJOBS_PORTSIR}/${TARGET}.naabu" ]]; then
	    cat ${CRONJOBS_SUBDOMAINDIR}/${TARGET}.subs | naabu -duc -silent -c ${NAABU_THREADS} -rate ${NAABU_RATELIMIT} -timeout ${NAABU_TIMEOUT} -retries ${NAABU_RETRIES} -top-ports 1000 2>/dev/null | unew -ef -el -i -t -q ${CRONJOBS_PORTSIR}/${TARGET}.naabu
	else
		cat ${CRONJOBS_SUBDOMAINDIR}/${TARGET}.subs | naabu -duc -silent -c ${NAABU_THREADS} -rate ${NAABU_RATELIMIT} -timeout ${NAABU_TIMEOUT} -retries ${NAABU_RETRIES} -top-ports 1000 2>/dev/null | unew -ef -el -i -t ${CRONJOBS_PORTSIR}/${TARGET}.naabu | unew -ef -el -i -t ${CRONJOBS_PORTSIR}/${TARGET}-new.naabu | notify -silent -duc -bulk -id subdomain-moniter &>/dev/null
	fi
}


# Alive Subdomain Scanning
MONITOR_ALIVESUBD(){
	if [[ ! -f "${CRONJOBS_ALIVE_SUBDOMAINDIR}/${TARGET}.alivesubs" ]]; then
	    cat ${CRONJOBS_PORTSIR}/${TARGET}.naabu | httpx -duc -silent -nc -sc -title -td -cl -t ${HTTPX_THREADS} | unew -ef -el -i -t -q ${CRONJOBS_ALIVE_SUBDOMAINDIR}/${TARGET}.alivesubs
	else
		cat ${CRONJOBS_PORTSIR}/${TARGET}.naabu | httpx -duc -silent -nc -sc -title -td -cl -t ${HTTPX_THREADS} | unew -ef -el -i -t ${CRONJOBS_ALIVE_SUBDOMAINDIR}/${TARGET}.alivesubs | unew -ef -el -i -t ${CRONJOBS_ALIVE_SUBDOMAINDIR}/${TARGET}-new.alivesubs | notify -silent -duc -bulk -id subdomain-moniter &>/dev/null
	fi
}


# Javascript Scanning
MONITOR_JS(){
	if [[ ! -f "${CRONJOBS_JSDIR}/${TARGET}.js" ]]; then
	    cat ${CRONJOBS_ALIVE_SUBDOMAINDIR}/${TARGET}.alivesubs | awk '{print $1}' | subjs | grep -aE "(https?://$TARGET(:[0-9]+)?(/)|\.$TARGET[:/])" | unew -ef -el -i -t -q ${CRONJOBS_JSDIR}/${TARGET}.js
	else
		cat ${CRONJOBS_ALIVE_SUBDOMAINDIR}/${TARGET}.alivesubs | awk '{print $1}' | subjs | grep -aE "(https?://$TARGET(:[0-9]+)?(/)|\.$TARGET[:/])" | unew -ef -el -i -t ${CRONJOBS_JSDIR}/${TARGET}.js | unew -ef -el -i -t ${CRONJOBS_JSDIR}/${TARGET}-new.js | notify -silent -duc -bulk -id subdomain-moniter &>/dev/null
	fi
}


# Javascript Leaks Scanning
MONITOR_JSLEAKS(){
	if [[ ! -f "${CRONJOBS_JSDIR}/${TARGET}.jsleaks" ]]; then
	    cat ${CRONJOBS_JSDIR}/${TARGET}.js | egrep -av "\.json" | grep -a "\.js" | linkinspector -silent -nc -mt "application/javascript" | awk '{print $1}' | unew -ef -el -i -t -q ${CRONJOBS_JSLEAKSDIR}/${TARGET}.jsleaks
	    cat ${CRONJOBS_JSDIR}/${TARGET}.js | nuclei -duc -silent -nc -t ~/nuclei-templates/exposures/ | unew -ef -el -i -t -q ${CRONJOBS_JSLEAKSDIR}/${TARGET}.jsleaks
	else
		cat ${CRONJOBS_JSDIR}/${TARGET}.js | egrep -av "\.json" | grep -a "\.js" | linkinspector -silent -nc -mt "application/javascript" | awk '{print $1}' | unew -ef -el -i -t ${CRONJOBS_JSLEAKSDIR}/${TARGET}.jsleaks | unew -ef -el -i -t ${CRONJOBS_JSLEAKSDIR}/${TARGET}-new.jsleaks | notify -silent -duc -bulk -id subdomain-moniter &>/dev/null
		cat ${CRONJOBS_JSDIR}/${TARGET}.js | nuclei -duc -silent -nc -t ~/nuclei-templates/exposures/ | unew -ef -el -i -t ${CRONJOBS_JSLEAKSDIR}/${TARGET}.jsleaks | unew -ef -el -i -t ${CRONJOBS_JSLEAKSDIR}/${TARGET}-new.jsleaks | notify -silent -duc -bulk -id subdomain-moniter &>/dev/null
	fi
}


# Dynamically call the selected function
$FUNC