#!/bin/bash

# Default config file path
CONFIG_PATH="configuration/garudrecon.cfg"

# Help function
function show_help() {
  cat <<EOF
This command sets up GarudRecon by installing the required tools and dependencies for a specified reconnaissance function. It supports installation for various predefined scopes such as SMALLSCOPE, MEDIUMSCOPE, LARGESCOPE, and CRONJOBS, or you can install everything at once using ALL.

You can also provide a custom configuration file and enable verbose output for more detailed installation logs.

Usage:
  garudrecon install [flags]

Flags:
  -f, --function        Function to run (e.g. MEDIUMSCOPE)
  -c, --config          Custom configuration file path
  -v, --verbose         enable verbose mode
  -h, --help            help for install

Example:
  garudrecon install -f SMALLSCOPE
  garudrecon install -f MEDIUMSCOPE
  garudrecon install -f LARGESCOPE
  garudrecon install -f CRONJOBS
  garudrecon install -f ALL
EOF
}

# Check if no args
if [[ $# -eq 0 ]]; then
  show_help
  exit 0
fi

# Parse arguments
while [[ "$#" -gt 0 ]]; do
  case "$1" in
    -f|--function)
      if [[ -z "$2" || "$2" == -* ]]; then
        echo "Error: -f requires a valid function argument"
        exit 1
      fi

      FUNC="$2"
      shift 2
      ;;
    -c|--config)
      CONFIG_PATH="$2"
      shift 2
      ;;
    -v|--verbose)
      VERBOSE=true
      shift
      ;;
    -h|--help)
      show_help
      exit 0
      ;;
    *)
      echo "Unknown option: $1"
      exit 1
      ;;
  esac
done

# Load configuration
if [[ -f "$CONFIG_PATH" ]]; then
    source "$CONFIG_PATH"
else
    echo "Error: Configuration file '$CONFIG_PATH' not found."
    exit 1
fi

PRINTBANNER

# Check root user
AREUROOTUSER

# Creating directories
mkdir -p wordlists
mkdir -p takeovers

# Function to handle CLEANUP on Ctrl+C
CLEANUP() {
    if [[ -n "$SPINNER_PID" ]]; then
        kill "$SPINNER_PID" 2>/dev/null
    fi
    exit 1
}
trap CLEANUP SIGINT

START_SPINNER() {
    processing="${1}"
    START_TIME=$(date +%s)
    BRAILLE_STYLE_SPINNER_CHARS=("⠋" "⠙" "⠹" "⠸" "⠼" "⠴" "⠦" "⠧" "⠇" "⠏")

    while true; do
    	ELAPSED=$(( $(date +%s) - START_TIME ))
        for char in "${BRAILLE_STYLE_SPINNER_CHARS[@]}"; do
            printf "${YELLOW}[${char}]${RESET} ${processing} ${CYAN}(${ELAPSED} seconds)${RESET} 🔎"
            printf "                                    \r"
            sleep 0.05
        done
    done &
    SPINNER_PID=$!
}

STOP_SPINNER() {
    kill "${SPINNER_PID}" 2>/dev/null
    TIME=$(( $(date +%s) - START_TIME ))
    return $TIME
}

echo -e "Using $CONFIG_PATH"


# VARIABLES
VARIABLES() {
    START_SPINNER "${BGREEN}VARIABLES${RESET}"
    echo -e "\n# xsel Variable" >> ~/.bashrc
    echo -e "alias xc='xsel -i -b'" >> ~/.bashrc
    echo -e "alias xp='xsel -o -b'" >> ~/.bashrc
    echo -e "alias cfile='explorer.exe .'" >> ~/.bashrc

    export PATH=$PATH:/usr/local/go/bin
    export PATH=$PATH:~/go/bin
    export PATH=$PATH:~/.local/bin
    export PATH=$PATH:~/.cargo/bin

    echo 'export PATH=$PATH:/usr/local/go/bin' >> ~/.bashrc
    echo 'export PATH=$PATH:~/go/bin' >> ~/.bashrc
    echo 'export PATH=$PATH:~/.local/bin' >> ~/.bashrc
    echo 'export PATH=$PATH:~/.cargo/bin' >> ~/.bashrc
    source ~/.bashrc

    STOP_SPINNER
    echo -e "${BGREEN}[+] VARIABLES - INSTALLED${RESET}: ${TIME} seconds"
}

# PACKAGES
PACKAGES() {
    START_SPINNER "${BGREEN}PACKAGES${RESET}"
    apt update -y &>/dev/null
    apt upgrade -y &>/dev/null

    # https://stackoverflow.com/questions/75602063/pip-install-r-requirements-txt-is-failing-this-environment-is-externally-mana
    rm -rf /usr/lib/python3.*/EXTERNALLY-MANAGED &>/dev/null

    STOP_SPINNER
    echo -e "${BGREEN}[+] PACKAGES - INSTALLED${RESET}: ${TIME} seconds"
}

PYTHON3() {
    START_SPINNER "${BGREEN}PYTHON3${RESET}"
    apt install python3 -y &>/dev/null

    if ! command -v python3 &>/dev/null; then
        echo -e "${BRED}[x] PYTHON3 - INSTALLATION FAILED${RESET}: ${TIME} seconds"
        STOP_SPINNER
        return
    fi

    STOP_SPINNER
    echo -e "${BGREEN}[+] PYTHON3 - INSTALLED${RESET}: ${TIME} seconds"
}

PYTHON3_PIP() {
    START_SPINNER "${BGREEN}PYTHON3_PIP${RESET}"
    apt install python3-pip -y &>/dev/null

    if ! command -v pip3 &>/dev/null; then
        echo -e "${BRED}[x] PYTHON3_PIP - INSTALLATION FAILED${RESET}: ${TIME} seconds"
        STOP_SPINNER
        return
    fi

    STOP_SPINNER
    echo -e "${BGREEN}[+] PYTHON3_PIP - INSTALLED${RESET}: ${TIME} seconds"
}

SETUPTOOLS() {
    START_SPINNER "${BGREEN}SETUPTOOLS${RESET}"
    pip3 install --upgrade setuptools --no-cache-dir &>/dev/null

    STOP_SPINNER
    echo -e "${BGREEN}[+] SETUPTOOLS - INSTALLED${RESET}: ${TIME} seconds"
}

GCC() {
    START_SPINNER "${BGREEN}GCC${RESET}"
    apt install gcc -y &>/dev/null

    if ! command -v gcc &>/dev/null; then
        echo -e "${BRED}[x] GCC - INSTALLATION FAILED${RESET}: ${TIME} seconds"
        STOP_SPINNER
        return
    fi

    STOP_SPINNER
    echo -e "${BGREEN}[+] GCC - INSTALLED${RESET}: ${TIME} seconds"
}

GIT() {
    START_SPINNER "${BGREEN}GIT${RESET}"
    apt install git -y &>/dev/null

    if ! command -v git &>/dev/null; then
        echo -e "${BRED}[x] GIT - INSTALLATION FAILED${RESET}: ${TIME} seconds"
        STOP_SPINNER
        return
    fi

    STOP_SPINNER
    echo -e "${BGREEN}[+] GIT - INSTALLED${RESET}: ${TIME} seconds"
}

PIPREQS() {
    START_SPINNER "${BGREEN}PIPREQS${RESET}"
    pip3 install pipreqs --no-cache-dir &>/dev/null

    if ! command -v pipreqs &>/dev/null; then
        echo -e "${BRED}[x] PIPREQS - INSTALLATION FAILED${RESET}: ${TIME} seconds"
        STOP_SPINNER
        return
    fi

    STOP_SPINNER
    echo -e "${BGREEN}[+] PIPREQS - INSTALLED${RESET}: ${TIME} seconds"
}

SSHPASS() {
    START_SPINNER "${BGREEN}SSHPASS${RESET}"
    apt install sshpass &>/dev/null

    if ! command -v sshpass &>/dev/null; then
        echo -e "${BRED}[x] SSHPASS - INSTALLATION FAILED${RESET}: ${TIME} seconds"
        STOP_SPINNER
        return
    fi

    STOP_SPINNER
    echo -e "${BGREEN}[+] SSHPASS - INSTALLED${RESET}: ${TIME} seconds"
}

CURL() {
    START_SPINNER "${BGREEN}CURL${RESET}"
    apt install curl -y &>/dev/null

    if ! command -v curl &>/dev/null; then
        echo -e "${BRED}[x] CURL - INSTALLATION FAILED${RESET}: ${TIME} seconds"
        STOP_SPINNER
        return
    fi

    STOP_SPINNER
    echo -e "${BGREEN}[+] CURL - INSTALLED${RESET}: ${TIME} seconds"
}

DOS2UNIX() {
    START_SPINNER "${BGREEN}DOS2UNIX${RESET}"
    apt install dos2unix &>/dev/null

    if ! command -v dos2unix &>/dev/null; then
        echo -e "${BRED}[x] DOS2UNIX - INSTALLATION FAILED${RESET}: ${TIME} seconds"
        STOP_SPINNER
        return
    fi

    STOP_SPINNER
    echo -e "${BGREEN}[+] DOS2UNIX - INSTALLED${RESET}: ${TIME} seconds"
}

WGET() {
    START_SPINNER "${BGREEN}WGET${RESET}"
    apt install wget -y &>/dev/null

    if ! command -v wget &>/dev/null; then
        echo -e "${BRED}[x] WGET - INSTALLATION FAILED${RESET}: ${TIME} seconds"
        STOP_SPINNER
        return
    fi

    STOP_SPINNER
    echo -e "${BGREEN}[+] WGET - INSTALLED${RESET}: ${TIME} seconds"
}

ZIP() {
    START_SPINNER "${BGREEN}ZIP${RESET}"
    apt install zip -y &>/dev/null

    if ! command -v zip &>/dev/null; then
        echo -e "${BRED}[x] ZIP - INSTALLATION FAILED${RESET}: ${TIME} seconds"
        STOP_SPINNER
        return
    fi

    STOP_SPINNER
    echo -e "${BGREEN}[+] ZIP - INSTALLED${RESET}: ${TIME} seconds"
}

XSEL() {
    START_SPINNER "${BGREEN}XSEL${RESET}"
    apt install xsel &>/dev/null

    if ! command -v xsel &>/dev/null; then
        echo -e "${BRED}[x] XSEL - INSTALLATION FAILED${RESET}: ${TIME} seconds"
        STOP_SPINNER
        return
    fi

    STOP_SPINNER
    echo -e "${BGREEN}[+] XSEL - INSTALLED${RESET}: ${TIME} seconds"
}

JQ() {
    START_SPINNER "${BGREEN}JQ${RESET}"
    apt install jq -y &>/dev/null

    if ! command -v jq &>/dev/null; then
        echo -e "${BRED}[x] JQ - INSTALLATION FAILED${RESET}: ${TIME} seconds"
        STOP_SPINNER
        return
    fi

    STOP_SPINNER
    echo -e "${BGREEN}[+] JQ - INSTALLED${RESET}: ${TIME} seconds"
}

YQ() {
    START_SPINNER "${BGREEN}YQ${RESET}"
    wget -q -O /usr/bin/yq https://github.com/mikefarah/yq/releases/latest/download/yq_linux_amd64 &>/dev/null
    chmod +x /usr/bin/yq

    if ! command -v yq &>/dev/null; then
        echo -e "${BRED}[x] YQ - INSTALLATION FAILED${RESET}: ${TIME} seconds"
        STOP_SPINNER
        return
    fi

    STOP_SPINNER
    echo -e "${BGREEN}[+] YQ - INSTALLED${RESET}: ${TIME} seconds"
}

LIBPCAP_DEV() {
    START_SPINNER "${BGREEN}LIBPCAP_DEV${RESET}"
    apt install libpcap-dev -y &>/dev/null

    STOP_SPINNER
    echo -e "${BGREEN}[+] LIBPCAP_DEV - INSTALLED${RESET}: ${TIME} seconds"
}

NPM() {
    START_SPINNER "${BGREEN}NPM${RESET}"
    apt install npm -y &>/dev/null

    if ! command -v npm &>/dev/null; then
        echo -e "${BRED}[x] NPM - INSTALLATION FAILED${RESET}: ${TIME} seconds"
        STOP_SPINNER
        return
    fi

    STOP_SPINNER
    echo -e "${BGREEN}[+] NPM - INSTALLED${RESET}: ${TIME} seconds"
}

CSV2JSON() {
    START_SPINNER "${BGREEN}CSV2JSON${RESET}"

    wget -q https://github.com/knadh/csv2json/releases/download/v0.1.1/csv2json_0.1.1_linux_amd64.tar.gz
    tar -xzf csv2json_0.1.1_linux_amd64.tar.gz
    mv csv2json /usr/local/bin/
    rm -rf csv2json_0.1.1_linux_amd64.tar.gz

    if ! command -v csv2json &>/dev/null; then
        echo -e "${BRED}[x] CSV2JSON - INSTALLATION FAILED${RESET}: ${TIME} seconds"
        STOP_SPINNER
        return
    fi

    STOP_SPINNER
    echo -e "${BGREEN}[+] CSV2JSON - INSTALLED${RESET}: ${TIME} seconds"
}

CSVTK() {
    START_SPINNER "${BGREEN}CSVTK${RESET}"

    wget -q https://github.com/shenwei356/csvtk/releases/download/v0.32.0/csvtk_linux_amd64.tar.gz
    tar -xzf csvtk_linux_amd64.tar.gz
    mv csvtk /usr/local/bin/
    rm -rf csvtk_linux_amd64.tar.gz

    if ! command -v csvtk &>/dev/null; then
        echo -e "${BRED}[x] CSVTK - INSTALLATION FAILED${RESET}: ${TIME} seconds"
        STOP_SPINNER
        return
    fi

    STOP_SPINNER
    echo -e "${BGREEN}[+] CSVTK - INSTALLED${RESET}: ${TIME} seconds"
}

PKG_CONFIG() {
    START_SPINNER "${BGREEN}PKG_CONFIG${RESET}"
    apt install pkg-config -y &>/dev/null

    STOP_SPINNER
    echo -e "${BGREEN}[+] PKG_CONFIG - INSTALLED${RESET}: ${TIME} seconds"
}

LIBUDEV_DEV() {
    START_SPINNER "${BGREEN}LIBUDEV_DEV${RESET}"
    apt install libudev-dev -y &>/dev/null

    STOP_SPINNER
    echo -e "${BGREEN}[+] LIBUDEV_DEV - INSTALLED${RESET}: ${TIME} seconds"
}

BUILD_ESSENTIAL() {
    START_SPINNER "${BGREEN}BUILD_ESSENTIAL${RESET}"
    apt install build-essential -y &>/dev/null

    STOP_SPINNER
    echo -e "${BGREEN}[+] BUILD_ESSENTIAL - INSTALLED${RESET}: ${TIME} seconds"
}

CHROMIUM() {
    START_SPINNER "${BGREEN}CHROMIUM${RESET}"
    apt install chromium -y &>/dev/null

    if ! command -v chromium &>/dev/null; then
        echo -e "${BRED}[x] CHROMIUM - INSTALLATION FAILED${RESET}: ${TIME} seconds"
        STOP_SPINNER
        return
    fi

    STOP_SPINNER
    echo -e "${BGREEN}[+] CHROMIUM - INSTALLED${RESET}: ${TIME} seconds"
}

CHROME() {
    START_SPINNER "${BGREEN}CHROME${RESET}"
    wget -q https://dl.google.com/linux/direct/google-chrome-stable_current_amd64.deb
    dpkg -i google-chrome-stable_current_amd64.deb &>/dev/null
    rm -rf google-chrome-stable_current_amd64.deb
    apt -f install -y &>/dev/null
    echo 'export PATH=$PATH:/usr/bin/google-chrome' >> ~/.bashrc
    source ~/.bashrc

    if ! command -v google-chrome &>/dev/null; then
        echo -e "${BRED}[x] CHROME - INSTALLATION FAILED${RESET}: ${TIME} seconds"
        STOP_SPINNER
        return
    fi

    STOP_SPINNER
    echo -e "${BGREEN}[+] CHROME - INSTALLED${RESET}: ${TIME} seconds"
}

PIPX() {
    START_SPINNER "${BGREEN}PIPX${RESET}"
    apt install pipx -y &>/dev/null

    if ! command -v pipx &>/dev/null; then
        echo -e "${BRED}[x] PIPX - INSTALLATION FAILED${RESET}: ${TIME} seconds"
        STOP_SPINNER
        return
    fi

    STOP_SPINNER
    echo -e "${BGREEN}[+] PIPX - INSTALLED${RESET}: ${TIME} seconds"
}

CMAKE() {
    START_SPINNER "${BGREEN}CMAKE${RESET}"
    apt install cmake -y &>/dev/null

    if ! command -v cmake &>/dev/null; then
        echo -e "${BRED}[x] CMAKE - INSTALLATION FAILED${RESET}: ${TIME} seconds"
        STOP_SPINNER
        return
    fi

    STOP_SPINNER
    echo -e "${BGREEN}[+] CMAKE - INSTALLED${RESET}: ${TIME} seconds"
}

RUST() {
    START_SPINNER "${BGREEN}RUST${RESET}"
    curl --proto '=https' --tlsv1.2 -sSf https://sh.rustup.rs | sh -s -- -y &>/dev/null
    source ~/.bashrc

    if ! command -v rustup &>/dev/null; then
        echo -e "${BRED}[x] RUSTUP - INSTALLATION FAILED${RESET}: ${TIME} seconds"
        STOP_SPINNER
        return
    fi

    if ! command -v rustc &>/dev/null; then
        echo -e "${BRED}[x] RUSTC - INSTALLATION FAILED${RESET}: ${TIME} seconds"
        STOP_SPINNER
        return
    fi

    if ! command -v cargo &>/dev/null; then
        echo -e "${BRED}[x] CARGO - INSTALLATION FAILED${RESET}: ${TIME} seconds"
        STOP_SPINNER
        return
    fi

    STOP_SPINNER
    echo -e "${BGREEN}[+] RUST - INSTALLED${RESET}: ${TIME} seconds"
}

PDFTOTEXT() {
    START_SPINNER "${BGREEN}PDFTOTEXT${RESET}"
    apt install poppler-utils -y &>/dev/null

    if ! command -v pdftotext &>/dev/null; then
        echo -e "${BRED}[x] PDFTOTEXT - INSTALLATION FAILED${RESET}: ${TIME} seconds"
        STOP_SPINNER
        return
    fi

    STOP_SPINNER
    echo -e "${BGREEN}[+] PDFTOTEXT - INSTALLED${RESET}: ${TIME} seconds"
}

PARALLEL() {
    START_SPINNER "${BGREEN}PARALLEL${RESET}"
    apt install parallel -y &>/dev/null

    if ! command -v parallel &>/dev/null; then
        echo -e "${BRED}[x] PARALLEL - INSTALLATION FAILED${RESET}: ${TIME} seconds"
        STOP_SPINNER
        return
    fi

    STOP_SPINNER
    echo -e "${BGREEN}[+] PARALLEL - INSTALLED${RESET}: ${TIME} seconds"
}

CEWL() {
    START_SPINNER "${BGREEN}CEWL${RESET}"
    apt install cewl -y &>/dev/null

    if ! command -v cewl &>/dev/null; then
        echo -e "${BRED}[x] CEWL - INSTALLATION FAILED${RESET}: ${TIME} seconds"
        STOP_SPINNER
        return
    fi

    STOP_SPINNER
    echo -e "${BGREEN}[+] CEWL - INSTALLED${RESET}: ${TIME} seconds"
}

PROXYCHAINS_SETUP() {
    START_SPINNER "${BGREEN}PROXYCHAINS_SETUP${RESET}"
    curl -s "https://raw.githubusercontent.com/rix4uni/proxychains_setup/main/setup.sh" | bash &>/dev/null

    if ! command -v proxychains &>/dev/null; then
        echo -e "${BRED}[x] PROXYCHAINS_SETUP - INSTALLATION FAILED${RESET}: ${TIME} seconds"
        STOP_SPINNER
        return
    fi

    STOP_SPINNER
    echo -e "${BGREEN}[+] PROXYCHAINS_SETUP - INSTALLED${RESET}: ${TIME} seconds"
}

GO() {
    START_SPINNER "${BGREEN}GO${RESET}"
    curl -s "https://gist.githubusercontent.com/rix4uni/c412ca956ea3bfa114bf4b615a9762bc/raw/91e9c8c93afbad3f16bdc41eb581f3e428dea9df/go.sh" | bash &>/dev/null

    if ! command -v go &>/dev/null; then
        echo -e "${BRED}[x] GO - INSTALLATION FAILED${RESET}: ${TIME} seconds"
        STOP_SPINNER
        return
    fi

    STOP_SPINNER
    echo -e "${BGREEN}[+] GO - INSTALLED${RESET}: ${TIME} seconds"
}

GOCL() {
    START_SPINNER "${BGREEN}GOCL${RESET}"
    wget -q https://github.com/rix4uni/gocl/releases/download/v0.0.4/gocl-linux-amd64-0.0.4.tgz
    tar -xvzf gocl-linux-amd64-0.0.4.tgz &>/dev/null
    rm -rf gocl-linux-amd64-0.0.4.tgz
    mkdir -p ~/go/bin
    mv gocl ~/go/bin/gocl

    if ! command -v gocl &>/dev/null; then
        echo -e "${BRED}[x] GOCL - INSTALLATION FAILED${RESET}: ${TIME} seconds"
        STOP_SPINNER
        return
    fi

    STOP_SPINNER
    echo -e "${BGREEN}[+] GOCL - INSTALLED${RESET}: ${TIME} seconds"
}

SHODAN() {
    START_SPINNER "${BGREEN}SHODAN${RESET}"
    apt install python3-shodan -y &>/dev/null

    if ! command -v shodan &>/dev/null; then
        echo -e "${BRED}[x] SHODAN - INSTALLATION FAILED${RESET}: ${TIME} seconds"
        STOP_SPINNER
        return
    fi

    STOP_SPINNER
    echo -e "${BGREEN}[+] SHODAN - INSTALLED${RESET}: ${TIME} seconds"
}

ARJUN() {
    START_SPINNER "${BGREEN}ARJUN${RESET}"
    pip3 install arjun --no-cache-dir &>/dev/null

    if ! command -v arjun &>/dev/null; then
        echo -e "${BRED}[x] ARJUN - INSTALLATION FAILED${RESET}: ${TIME} seconds"
        STOP_SPINNER
        return
    fi

    STOP_SPINNER
    echo -e "${BGREEN}[+] ARJUN - INSTALLED${RESET}: ${TIME} seconds"
}

TLDINFO() {
    START_SPINNER "${BGREEN}TLDINFO${RESET}"
    pipx install --force git+https://github.com/rix4uni/tldinfo.git &>/dev/null

    if ! command -v tldinfo &>/dev/null; then
        echo -e "${BRED}[x] TLDINFO - INSTALLATION FAILED${RESET}: ${TIME} seconds"
        STOP_SPINNER
        return
    fi

    STOP_SPINNER
    echo -e "${BGREEN}[+] TLDINFO - INSTALLED${RESET}: ${TIME} seconds"
}

SUBWIZ() {
    START_SPINNER "${BGREEN}SUBWIZ${RESET}"
    pipx install --force git+https://github.com/hadriansecurity/subwiz.git &>/dev/null

    if ! command -v subwiz &>/dev/null; then
        echo -e "${BRED}[x] SUBWIZ - INSTALLATION FAILED${RESET}: ${TIME} seconds"
        STOP_SPINNER
        return
    fi

    STOP_SPINNER
    echo -e "${BGREEN}[+] SUBWIZ - INSTALLED${RESET}: ${TIME} seconds"
}

URO() {
    START_SPINNER "${BGREEN}URO${RESET}"
    pip3 install uro --no-cache-dir &>/dev/null

    if ! command -v uro &>/dev/null; then
        echo -e "${BRED}[x] URO - INSTALLATION FAILED${RESET}: ${TIME} seconds"
        STOP_SPINNER
        return
    fi

    STOP_SPINNER
    echo -e "${BGREEN}[+] URO - INSTALLED${RESET}: ${TIME} seconds"
}

X8() {
    START_SPINNER "${BGREEN}X8${RESET}"
    wget -q https://github.com/Sh1Yo/x8/releases/download/v4.3.0/x86_64-linux-x8.gz
    gunzip x86_64-linux-x8.gz
    mv x86_64-linux-x8 x8
    chmod +x x8
    mv x8 /usr/local/bin

    if ! command -v x8 &>/dev/null; then
        echo -e "${BRED}[x] X8 - INSTALLATION FAILED${RESET}: ${TIME} seconds"
        STOP_SPINNER
        return
    fi

    STOP_SPINNER
    echo -e "${BGREEN}[+] X8 - INSTALLED${RESET}: ${TIME} seconds"
}

FINDOMAIN() {
    START_SPINNER "${BGREEN}FINDOMAIN${RESET}"
    wget -q https://github.com/Findomain/Findomain/releases/download/9.0.4/findomain-linux.zip
    unzip -q findomain-linux.zip
    rm -rf findomain-linux.zip
    chmod +x findomain
    mv findomain /usr/bin/

    if ! command -v findomain &>/dev/null; then
        echo -e "${BRED}[x] FINDOMAIN - INSTALLATION FAILED${RESET}: ${TIME} seconds"
        STOP_SPINNER
        return
    fi

    STOP_SPINNER
    echo -e "${BGREEN}[+] FINDOMAIN - INSTALLED${RESET}: ${TIME} seconds"
}

BBOT() {
    START_SPINNER "${BGREEN}BBOT${RESET}"
    pipx install --force bbot &>/dev/null

    if ! command -v bbot &>/dev/null; then
        echo -e "${BRED}[x] BBOT - INSTALLATION FAILED${RESET}: ${TIME} seconds"
        STOP_SPINNER
        return
    fi

    STOP_SPINNER
    echo -e "${BGREEN}[+] BBOT - INSTALLED${RESET}: ${TIME} seconds"
}

WAYMORE() {
    START_SPINNER "${BGREEN}WAYMORE${RESET}"
    pip3 install waymore --no-cache-dir &>/dev/null

    if ! command -v waymore &>/dev/null; then
        echo -e "${BRED}[x] WAYMORE - INSTALLATION FAILED${RESET}: ${TIME} seconds"
        STOP_SPINNER
        return
    fi

    STOP_SPINNER
    echo -e "${BGREEN}[+] WAYMORE - INSTALLED${RESET}: ${TIME} seconds"
}

XNLINKFINDER() {
    START_SPINNER "${BGREEN}XNLINKFINDER${RESET}"
    pip3 install xnLinkFinder --no-cache-dir &>/dev/null

    if ! command -v xnLinkFinder &>/dev/null; then
        echo -e "${BRED}[x] XNLINKFINDER - INSTALLATION FAILED${RESET}: ${TIME} seconds"
        STOP_SPINNER
        return
    fi

    STOP_SPINNER
    echo -e "${BGREEN}[+] XNLINKFINDER - INSTALLED${RESET}: ${TIME} seconds"
}

FEROXBUSTER() {
    START_SPINNER "${BGREEN}FEROXBUSTER${RESET}"
    wget -q https://github.com/epi052/feroxbuster/releases/download/v2.11.0/feroxbuster_amd64.deb.zip &>/dev/null
    unzip -q feroxbuster_amd64.deb.zip
    dpkg -i feroxbuster_2.11.0-1_amd64.deb &>/dev/null
    rm -rf feroxbuster_amd64.deb.zip feroxbuster_2.11.0-1_amd64.deb

    if ! command -v feroxbuster &>/dev/null; then
        echo -e "${BRED}[x] FEROXBUSTER - INSTALLATION FAILED${RESET}: ${TIME} seconds"
        STOP_SPINNER
        return
    fi

    STOP_SPINNER
    echo -e "${BGREEN}[+] FEROXBUSTER - INSTALLED${RESET}: ${TIME} seconds"
}

ALTDNS() {
    START_SPINNER "${BGREEN}ALTDNS${RESET}"
    pipx install --force git+https://github.com/infosec-au/altdns.git &>/dev/null

    if ! command -v altdns &>/dev/null; then
        echo -e "${BRED}[x] ALTDNS - INSTALLATION FAILED${RESET}: ${TIME} seconds"
        STOP_SPINNER
        return
    fi

    STOP_SPINNER
    echo -e "${BGREEN}[+] ALTDNS - INSTALLED${RESET}: ${TIME} seconds"
}

MASSCAN() {
    START_SPINNER "${BGREEN}MASSCAN${RESET}"
    git clone https://github.com/robertdavidgraham/masscan.git --depth 1 &>/dev/null
    cd masscan
    make &>/dev/null
    make install &>/dev/null
    cd ..
    rm -rf masscan

    if ! command -v masscan &>/dev/null; then
        echo -e "${BRED}[x] MASSCAN - INSTALLATION FAILED${RESET}: ${TIME} seconds"
        STOP_SPINNER
        return
    fi

    STOP_SPINNER
    echo -e "${BGREEN}[+] MASSCAN - INSTALLED${RESET}: ${TIME} seconds"
}

MASSDNS() {
    START_SPINNER "${BGREEN}MASSDNS${RESET}"
    git clone https://github.com/blechschmidt/massdns.git --depth 1 &>/dev/null
    cd massdns
    make &>/dev/null
    make install &>/dev/null
    cd ..
    rm -rf massdns

    if ! command -v massdns &>/dev/null; then
        echo -e "${BRED}[x] MASSDNS - INSTALLATION FAILED${RESET}: ${TIME} seconds"
        STOP_SPINNER
        return
    fi

    STOP_SPINNER
    echo -e "${BGREEN}[+] MASSDNS - INSTALLED${RESET}: ${TIME} seconds"
}

RUSTSCAN() {
    START_SPINNER "${BGREEN}RUSTSCAN${RESET}"
    wget -q https://github.com/RustScan/RustScan/releases/download/2.3.0/rustscan-2.3.0-x86_64-linux.zip
    unzip -q rustscan-2.3.0-x86_64-linux.zip
    chmod +x tmp/rustscan-2.3.0-x86_64-linux/rustscan
    mv tmp/rustscan-2.3.0-x86_64-linux/rustscan /usr/bin/
    rm -rf rustscan-2.3.0-x86_64-linux.zip tmp

    if ! command -v rustscan &>/dev/null; then
        echo -e "${BRED}[x] RUSTSCAN - INSTALLATION FAILED${RESET}: ${TIME} seconds"
        STOP_SPINNER
        return
    fi

    STOP_SPINNER
    echo -e "${BGREEN}[+] RUSTSCAN - INSTALLED${RESET}: ${TIME} seconds"
}

GHAURI() {
    START_SPINNER "${BGREEN}GHAURI${RESET}"
    # pipx install --force git+https://github.com/r0oth3x49/ghauri.git &>/dev/null

    git clone https://github.com/r0oth3x49/ghauri.git --depth 1 &>/dev/null
    cd ghauri
    sed -i '/class SmartRedirectHandler/,/http_error_301/ s/user_input="Y"/user_input="n"/' ghauri/common/utils.py
    python3 setup.py install &>/dev/null
    cd ..
    rm -rf ghauri

    if ! command -v ghauri &>/dev/null; then
        echo -e "${BRED}[x] GHAURI - INSTALLATION FAILED${RESET}: ${TIME} seconds"
        STOP_SPINNER
        return
    fi

    STOP_SPINNER
    echo -e "${BGREEN}[+] GHAURI - INSTALLED${RESET}: ${TIME} seconds"
}

SQLMAP() {
    START_SPINNER "${BGREEN}SQLMAP${RESET}"
    git clone https://github.com/sqlmapproject/sqlmap.git --depth 1 tools/sqlmap &>/dev/null
    sed -i "s/kb.choices.redirect = REDIRECTION.YES if readInput(msg, default='Y', boolean=True) else REDIRECTION.NO/kb.choices.redirect = REDIRECTION.YES if readInput(msg, default='n', boolean=True) else REDIRECTION.NO/g" tools/sqlmap/lib/request/redirecthandler.py

    if ! command -v sqlmap &>/dev/null; then
        echo -e "${BRED}[x] SQLMAP - INSTALLATION FAILED${RESET}: ${TIME} seconds"
        STOP_SPINNER
        return
    fi

    STOP_SPINNER
    echo -e "${BGREEN}[+] SQLMAP - INSTALLED${RESET}: ${TIME} seconds"
}

INTERLACE() {
    START_SPINNER "${BGREEN}INTERLACE${RESET}"
    pipx install --force git+https://github.com/codingo/Interlace.git &>/dev/null

    if ! command -v interlace &>/dev/null; then
        echo -e "${BRED}[x] INTERLACE - INSTALLATION FAILED${RESET}: ${TIME} seconds"
        STOP_SPINNER
        return
    fi

    STOP_SPINNER
    echo -e "${BGREEN}[+] INTERLACE - INSTALLED${RESET}: ${TIME} seconds"
}

HTTPX() {
    START_SPINNER "${BGREEN}HTTPX${RESET}"
    gocl -i github.com/projectdiscovery/httpx &>/dev/null

    if ! command -v httpx &>/dev/null; then
        echo -e "${BRED}[x] HTTPX - INSTALLATION FAILED${RESET}: ${TIME} seconds"
        STOP_SPINNER
        return
    fi

    STOP_SPINNER
    echo -e "${BGREEN}[+] HTTPX - INSTALLED${RESET}: ${TIME} seconds"
}

XSUBFIND3R() {
    START_SPINNER "${BGREEN}XSUBFIND3R${RESET}"
    gocl -i github.com/hueristiq/xsubfind3r -c "cmd/xsubfind3r" &>/dev/null

    if ! command -v xsubfind3r &>/dev/null; then
        echo -e "${BRED}[x] XSUBFIND3R - INSTALLATION FAILED${RESET}: ${TIME} seconds"
        STOP_SPINNER
        return
    fi

    STOP_SPINNER
    echo -e "${BGREEN}[+] XSUBFIND3R - INSTALLED${RESET}: ${TIME} seconds"
}

JSUBFINDER() {
    START_SPINNER "${BGREEN}JSUBFINDER${RESET}"
    gocl -i github.com/ThreatUnkown/jsubfinder &>/dev/null

    if ! command -v jsubfinder &>/dev/null; then
        echo -e "${BRED}[x] JSUBFINDER - INSTALLATION FAILED${RESET}: ${TIME} seconds"
        STOP_SPINNER
        return
    fi

    STOP_SPINNER
    echo -e "${BGREEN}[+] JSUBFINDER - INSTALLED${RESET}: ${TIME} seconds"
}

NUCLEI() {
    START_SPINNER "${BGREEN}NUCLEI${RESET}"
    gocl -i github.com/projectdiscovery/nuclei &>/dev/null

    if ! command -v nuclei &>/dev/null; then
        echo -e "${BRED}[x] NUCLEI - INSTALLATION FAILED${RESET}: ${TIME} seconds"
        STOP_SPINNER
        return
    fi

    STOP_SPINNER
    echo -e "${BGREEN}[+] NUCLEI - INSTALLED${RESET}: ${TIME} seconds"
}

NUCLEI_TEMPLATE() {
    START_SPINNER "${BGREEN}NUCLEI_TEMPLATE${RESET}"
    nuclei -silent -update-templates &>/dev/null
    git clone https://github.com/rix4uni/nucleihub-templates.git --depth 1 ~/nucleihub-templates &>/dev/null

    mkdir -p templates
    cp -r ~/nuclei-templates/http/takeovers templates/takeovers
    sed -i '/- type: dsl/{N;N;/Host != ip/{N;/^$/d;d;}}' templates/takeovers/*.yaml &>/dev/null

    STOP_SPINNER
    echo -e "${BGREEN}[+] NUCLEI_TEMPLATE - INSTALLED${RESET}: ${TIME} seconds"
}

SUBFINDER() {
    START_SPINNER "${BGREEN}SUBFINDER${RESET}"
    gocl -i github.com/projectdiscovery/subfinder &>/dev/null

    if ! command -v subfinder &>/dev/null; then
        echo -e "${BRED}[x] SUBFINDER - INSTALLATION FAILED${RESET}: ${TIME} seconds"
        STOP_SPINNER
        return
    fi

    STOP_SPINNER
    echo -e "${BGREEN}[+] SUBFINDER - INSTALLED${RESET}: ${TIME} seconds"
}

CVEMAP() {
    START_SPINNER "${BGREEN}CVEMAP${RESET}"
    gocl -i github.com/projectdiscovery/cvemap &>/dev/null

    if ! command -v cvemap &>/dev/null; then
        echo -e "${BRED}[x] CVEMAP - INSTALLATION FAILED${RESET}: ${TIME} seconds"
        STOP_SPINNER
        return
    fi

    STOP_SPINNER
    echo -e "${BGREEN}[+] CVEMAP - INSTALLED${RESET}: ${TIME} seconds"
}

KATANA() {
    START_SPINNER "${BGREEN}KATANA${RESET}"
    gocl -i github.com/projectdiscovery/katana &>/dev/null

    if ! command -v katana &>/dev/null; then
        echo -e "${BRED}[x] KATANA - INSTALLATION FAILED${RESET}: ${TIME} seconds"
        STOP_SPINNER
        return
    fi

    STOP_SPINNER
    echo -e "${BGREEN}[+] KATANA - INSTALLED${RESET}: ${TIME} seconds"
}

NAABU() {
    START_SPINNER "${BGREEN}NAABU${RESET}"
    gocl -i github.com/projectdiscovery/naabu &>/dev/null

    if ! command -v naabu &>/dev/null; then
        echo -e "${BRED}[x] NAABU - INSTALLATION FAILED${RESET}: ${TIME} seconds"
        STOP_SPINNER
        return
    fi

    STOP_SPINNER
    echo -e "${BGREEN}[+] NAABU - INSTALLED${RESET}: ${TIME} seconds"
}

NMAP() {
    START_SPINNER "${BGREEN}NMAP${RESET}"
    git clone https://github.com/nmap/nmap.git --depth 1 &>/dev/null
    cd nmap
    ./configure &>/dev/null
    make &>/dev/null
    make install &>/dev/null
    cd ..
    rm -rf nmap

    if ! command -v naabu &>/dev/null; then
        echo -e "${BRED}[x] NMAP - INSTALLATION FAILED${RESET}: ${TIME} seconds"
        STOP_SPINNER
        return
    fi

    STOP_SPINNER
    echo -e "${BGREEN}[+] NMAP - INSTALLED${RESET}: ${TIME} seconds"
}

MAPCIDR() {
    START_SPINNER "${BGREEN}MAPCIDR${RESET}"
    gocl -i github.com/projectdiscovery/mapcidr &>/dev/null

    if ! command -v mapcidr &>/dev/null; then
        echo -e "${BRED}[x] MAPCIDR - INSTALLATION FAILED${RESET}: ${TIME} seconds"
        STOP_SPINNER
        return
    fi

    STOP_SPINNER
    echo -e "${BGREEN}[+] MAPCIDR - INSTALLED${RESET}: ${TIME} seconds"
}

SHUFFLEDNS() {
    START_SPINNER "${BGREEN}SHUFFLEDNS${RESET}"
    gocl -i github.com/projectdiscovery/shuffledns &>/dev/null

    if ! command -v shuffledns &>/dev/null; then
        echo -e "${BRED}[x] SHUFFLEDNS - INSTALLATION FAILED${RESET}: ${TIME} seconds"
        STOP_SPINNER
        return
    fi

    STOP_SPINNER
    echo -e "${BGREEN}[+] SHUFFLEDNS - INSTALLED${RESET}: ${TIME} seconds"
}

UNCOVER() {
    START_SPINNER "${BGREEN}UNCOVER${RESET}"
    gocl -i github.com/projectdiscovery/uncover &>/dev/null

    if ! command -v uncover &>/dev/null; then
        echo -e "${BRED}[x] UNCOVER - INSTALLATION FAILED${RESET}: ${TIME} seconds"
        STOP_SPINNER
        return
    fi

    STOP_SPINNER
    echo -e "${BGREEN}[+] UNCOVER - INSTALLED${RESET}: ${TIME} seconds"
}

ASNMAP() {
    START_SPINNER "${BGREEN}ASNMAP${RESET}"
    gocl -i github.com/projectdiscovery/asnmap &>/dev/null

    if ! command -v asnmap &>/dev/null; then
        echo -e "${BRED}[x] ASNMAP - INSTALLATION FAILED${RESET}: ${TIME} seconds"
        STOP_SPINNER
        return
    fi

    STOP_SPINNER
    echo -e "${BGREEN}[+] ASNMAP - INSTALLED${RESET}: ${TIME} seconds"
}

CDNCHECK() {
    START_SPINNER "${BGREEN}CDNCHECK${RESET}"
    gocl -i github.com/projectdiscovery/cdncheck &>/dev/null

    if ! command -v cdncheck &>/dev/null; then
        echo -e "${BRED}[x] CDNCHECK - INSTALLATION FAILED${RESET}: ${TIME} seconds"
        STOP_SPINNER
        return
    fi

    STOP_SPINNER
    echo -e "${BGREEN}[+] CDNCHECK - INSTALLED${RESET}: ${TIME} seconds"
}

DNSX() {
    START_SPINNER "${BGREEN}DNSX${RESET}"
    gocl -i github.com/projectdiscovery/dnsx &>/dev/null

    if ! command -v dnsx &>/dev/null; then
        echo -e "${BRED}[x] DNSX - INSTALLATION FAILED${RESET}: ${TIME} seconds"
        STOP_SPINNER
        return
    fi

    STOP_SPINNER
    echo -e "${BGREEN}[+] DNSX - INSTALLED${RESET}: ${TIME} seconds"
}

CHAOS() {
    START_SPINNER "${BGREEN}CHAOS${RESET}"
    gocl -i github.com/projectdiscovery/chaos-client -c "cmd/chaos" &>/dev/null

    if ! command -v chaos &>/dev/null; then
        echo -e "${BRED}[x] CHAOS - INSTALLATION FAILED${RESET}: ${TIME} seconds"
        STOP_SPINNER
        return
    fi

    STOP_SPINNER
    echo -e "${BGREEN}[+] CHAOS - INSTALLED${RESET}: ${TIME} seconds"
}

TLDFINDER() {
    START_SPINNER "${BGREEN}TLDFINDER${RESET}"
    gocl -i github.com/projectdiscovery/tldfinder &>/dev/null

    if ! command -v tldfinder &>/dev/null; then
        echo -e "${BRED}[x] TLDFINDER - INSTALLATION FAILED${RESET}: ${TIME} seconds"
        STOP_SPINNER
        return
    fi

    STOP_SPINNER
    echo -e "${BGREEN}[+] TLDFINDER - INSTALLED${RESET}: ${TIME} seconds"
}

ALTERX() {
    START_SPINNER "${BGREEN}ALTERX${RESET}"
    gocl -i github.com/projectdiscovery/alterx &>/dev/null

    if ! command -v alterx &>/dev/null; then
        echo -e "${BRED}[x] ALTERX - INSTALLATION FAILED${RESET}: ${TIME} seconds"
        STOP_SPINNER
        return
    fi

    STOP_SPINNER
    echo -e "${BGREEN}[+] ALTERX - INSTALLED${RESET}: ${TIME} seconds"
}

TLSX() {
    START_SPINNER "${BGREEN}TLSX${RESET}"
    gocl -i github.com/projectdiscovery/tlsx &>/dev/null

    if ! command -v tlsx &>/dev/null; then
        echo -e "${BRED}[x] TLSX - INSTALLATION FAILED${RESET}: ${TIME} seconds"
        STOP_SPINNER
        return
    fi

    STOP_SPINNER
    echo -e "${BGREEN}[+] TLSX - INSTALLED${RESET}: ${TIME} seconds"
}

INTERACTSH_CLIENT() {
    START_SPINNER "${BGREEN}INTERACTSH_CLIENT${RESET}"
    gocl -i github.com/projectdiscovery/interactsh -c "cmd/interactsh-client" &>/dev/null

    if ! command -v interactsh-client &>/dev/null; then
        echo -e "${BRED}[x] INTERACTSH_CLIENT - INSTALLATION FAILED${RESET}: ${TIME} seconds"
        STOP_SPINNER
        return
    fi

    STOP_SPINNER
    echo -e "${BGREEN}[+] INTERACTSH_CLIENT - INSTALLED${RESET}: ${TIME} seconds"
}

NOTIFY() {
    START_SPINNER "${BGREEN}NOTIFY${RESET}"
    gocl -i github.com/projectdiscovery/notify &>/dev/null

    if ! command -v notify &>/dev/null; then
        echo -e "${BRED}[x] NOTIFY - INSTALLATION FAILED${RESET}: ${TIME} seconds"
        STOP_SPINNER
        return
    fi

    STOP_SPINNER
    echo -e "${BGREEN}[+] NOTIFY - INSTALLED${RESET}: ${TIME} seconds"
}

HTTPROBE() {
    START_SPINNER "${BGREEN}HTTPROBE${RESET}"
    gocl -i github.com/tomnomnom/httprobe &>/dev/null

    if ! command -v httprobe &>/dev/null; then
        echo -e "${BRED}[x] HTTPROBE - INSTALLATION FAILED${RESET}: ${TIME} seconds"
        STOP_SPINNER
        return
    fi

    STOP_SPINNER
    echo -e "${BGREEN}[+] HTTPROBE - INSTALLED${RESET}: ${TIME} seconds"
}

ASSETFINDER() {
    START_SPINNER "${BGREEN}ASSETFINDER${RESET}"
    gocl -i github.com/tomnomnom/assetfinder &>/dev/null

    if ! command -v assetfinder &>/dev/null; then
        echo -e "${BRED}[x] ASSETFINDER - INSTALLATION FAILED${RESET}: ${TIME} seconds"
        STOP_SPINNER
        return
    fi

    STOP_SPINNER
    echo -e "${BGREEN}[+] ASSETFINDER - INSTALLED${RESET}: ${TIME} seconds"
}

WAYBACKURLS() {
    START_SPINNER "${BGREEN}WAYBACKURLS${RESET}"
    gocl -i github.com/tomnomnom/waybackurls &>/dev/null

    if ! command -v waybackurls &>/dev/null; then
        echo -e "${BRED}[x] WAYBACKURLS - INSTALLATION FAILED${RESET}: ${TIME} seconds"
        STOP_SPINNER
        return
    fi

    STOP_SPINNER
    echo -e "${BGREEN}[+] WAYBACKURLS - INSTALLED${RESET}: ${TIME} seconds"
}

FFF() {
    START_SPINNER "${BGREEN}FFF${RESET}"
    gocl -i github.com/tomnomnom/fff &>/dev/null

    if ! command -v fff &>/dev/null; then
        echo -e "${BRED}[x] FFF - INSTALLATION FAILED${RESET}: ${TIME} seconds"
        STOP_SPINNER
        return
    fi

    STOP_SPINNER
    echo -e "${BGREEN}[+] FFF - INSTALLED${RESET}: ${TIME} seconds"
}

MEG() {
    START_SPINNER "${BGREEN}MEG${RESET}"
    gocl -i github.com/tomnomnom/meg &>/dev/null

    if ! command -v meg &>/dev/null; then
        echo -e "${BRED}[x] MEG - INSTALLATION FAILED${RESET}: ${TIME} seconds"
        STOP_SPINNER
        return
    fi

    STOP_SPINNER
    echo -e "${BGREEN}[+] MEG - INSTALLED${RESET}: ${TIME} seconds"
}

ANEW() {
    START_SPINNER "${BGREEN}ANEW${RESET}"
    gocl -i github.com/tomnomnom/anew &>/dev/null

    if ! command -v anew &>/dev/null; then
        echo -e "${BRED}[x] ANEW - INSTALLATION FAILED${RESET}: ${TIME} seconds"
        STOP_SPINNER
        return
    fi

    STOP_SPINNER
    echo -e "${BGREEN}[+] ANEW - INSTALLED${RESET}: ${TIME} seconds"
}

GRON() {
    START_SPINNER "${BGREEN}GRON${RESET}"
    gocl -i github.com/tomnomnom/gron &>/dev/null

    if ! command -v gron &>/dev/null; then
        echo -e "${BRED}[x] GRON - INSTALLATION FAILED${RESET}: ${TIME} seconds"
        STOP_SPINNER
        return
    fi

    STOP_SPINNER
    echo -e "${BGREEN}[+] GRON - INSTALLED${RESET}: ${TIME} seconds"
}

UNFURL() {
    START_SPINNER "${BGREEN}UNFURL${RESET}"
    gocl -i github.com/tomnomnom/unfurl &>/dev/null

    if ! command -v unfurl &>/dev/null; then
        echo -e "${BRED}[x] UNFURL - INSTALLATION FAILED${RESET}: ${TIME} seconds"
        STOP_SPINNER
        return
    fi

    STOP_SPINNER
    echo -e "${BGREEN}[+] UNFURL - INSTALLED${RESET}: ${TIME} seconds"
}

GF() {
    START_SPINNER "${BGREEN}GF${RESET}"
    gocl -i github.com/tomnomnom/gf &>/dev/null

    if ! command -v gf &>/dev/null; then
        echo -e "${BRED}[x] GF - INSTALLATION FAILED${RESET}: ${TIME} seconds"
        STOP_SPINNER
        return
    fi

    STOP_SPINNER
    echo -e "${BGREEN}[+] GF - INSTALLED${RESET}: ${TIME} seconds"
}

GF_PATTERNS() {
    START_SPINNER "${BGREEN}GF_PATTERNS${RESET}"
    git clone https://github.com/rix4uni/gf-patterns.git --depth 1 ~/.gf &>/dev/null

    STOP_SPINNER
    echo -e "${BGREEN}[+] GF_PATTERNS - INSTALLED${RESET}: ${TIME} seconds"
}

QSREPLACE() {
    START_SPINNER "${BGREEN}QSREPLACE${RESET}"
    gocl -i github.com/tomnomnom/qsreplace &>/dev/null

    if ! command -v qsreplace &>/dev/null; then
        echo -e "${BRED}[x] QSREPLACE - INSTALLATION FAILED${RESET}: ${TIME} seconds"
        STOP_SPINNER
        return
    fi

    STOP_SPINNER
    echo -e "${BGREEN}[+] QSREPLACE - INSTALLED${RESET}: ${TIME} seconds"
}

SUBDOG() {
    START_SPINNER "${BGREEN}SUBDOG${RESET}"
    gocl -i github.com/rix4uni/subdog &>/dev/null

    if ! command -v subdog &>/dev/null; then
        echo -e "${BRED}[x] SUBDOG - INSTALLATION FAILED${RESET}: ${TIME} seconds"
        STOP_SPINNER
        return
    fi

    STOP_SPINNER
    echo -e "${BGREEN}[+] SUBDOG - INSTALLED${RESET}: ${TIME} seconds"
}

HAKTRAILSFREE() {
    START_SPINNER "${BGREEN}HAKTRAILSFREE${RESET}"
    gocl -i github.com/rix4uni/haktrailsfree &>/dev/null

    if ! command -v haktrailsfree &>/dev/null; then
        echo -e "${BRED}[x] HAKTRAILSFREE - INSTALLATION FAILED${RESET}: ${TIME} seconds"
        STOP_SPINNER
        return
    fi

    STOP_SPINNER
    echo -e "${BGREEN}[+] HAKTRAILSFREE - INSTALLED${RESET}: ${TIME} seconds"
}

ORG2ASN() {
    START_SPINNER "${BGREEN}ORG2ASN${RESET}"
    gocl -i github.com/rix4uni/org2asn &>/dev/null

    if ! command -v org2asn &>/dev/null; then
        echo -e "${BRED}[x] ORG2ASN - INSTALLATION FAILED${RESET}: ${TIME} seconds"
        STOP_SPINNER
        return
    fi

    STOP_SPINNER
    echo -e "${BGREEN}[+] ORG2ASN - INSTALLED${RESET}: ${TIME} seconds"
}

WHOXYSUBS() {
    START_SPINNER "${BGREEN}WHOXYSUBS${RESET}"
    gocl -i github.com/rix4uni/whoxysubs &>/dev/null

    if ! command -v whoxysubs &>/dev/null; then
        echo -e "${BRED}[x] WHOXYSUBS - INSTALLATION FAILED${RESET}: ${TIME} seconds"
        STOP_SPINNER
        return
    fi

    STOP_SPINNER
    echo -e "${BGREEN}[+] WHOXYSUBS - INSTALLED${RESET}: ${TIME} seconds"
}

UDON() {
    START_SPINNER "${BGREEN}UDON${RESET}"
    gocl -i github.com/dhn/udon &>/dev/null

    if ! command -v udon &>/dev/null; then
        echo -e "${BRED}[x] UDON - INSTALLATION FAILED${RESET}: ${TIME} seconds"
        STOP_SPINNER
        return
    fi

    STOP_SPINNER
    echo -e "${BGREEN}[+] UDON - INSTALLED${RESET}: ${TIME} seconds"
}

TECHX() {
    START_SPINNER "${BGREEN}TECHX${RESET}"
    gocl -i github.com/rix4uni/techx &>/dev/null

    if ! command -v techx &>/dev/null; then
        echo -e "${BRED}[x] TECHX - INSTALLATION FAILED${RESET}: ${TIME} seconds"
        STOP_SPINNER
        return
    fi

    STOP_SPINNER
    echo -e "${BGREEN}[+] TECHX - INSTALLED${RESET}: ${TIME} seconds"
}

UNEW() {
    START_SPINNER "${BGREEN}UNEW${RESET}"
    gocl -i github.com/rix4uni/unew &>/dev/null

    if ! command -v unew &>/dev/null; then
        echo -e "${BRED}[x] UNEW - INSTALLATION FAILED${RESET}: ${TIME} seconds"
        STOP_SPINNER
        return
    fi

    STOP_SPINNER
    echo -e "${BGREEN}[+] UNEW - INSTALLED${RESET}: ${TIME} seconds"
}

UNEWFLUSH() {
    START_SPINNER "${BGREEN}UNEWFLUSH${RESET}"
    # This is unew flush version only for gungnir saves output immediately in a file.
    git clone https://github.com/rix4uni/unew.git --depth 1 unewflush &>/dev/null
    cd unewflush
    mv unew.go unewflush.go
    sed -i 's/unew/unewflush/' go.mod
    sed -i '/w\.WriteString(line + "\\n")/a \\t\t\t\t\tw.Flush() // Flush immediately after writing' unewflush.go
    go install &>/dev/null
    cd ..
    rm -rf unewflush

    if ! command -v unewflush &>/dev/null; then
        echo -e "${BRED}[x] UNEWFLUSH - INSTALLATION FAILED${RESET}: ${TIME} seconds"
        STOP_SPINNER
        return
    fi

    STOP_SPINNER
    echo -e "${BGREEN}[+] UNEWFLUSH - INSTALLED${RESET}: ${TIME} seconds"
}

IP2ORG() {
    START_SPINNER "${BGREEN}IP2ORG${RESET}"
    gocl -i github.com/rix4uni/ip2org &>/dev/null

    if ! command -v ip2org &>/dev/null; then
        echo -e "${BRED}[x] IP2ORG - INSTALLATION FAILED${RESET}: ${TIME} seconds"
        STOP_SPINNER
        return
    fi

    STOP_SPINNER
    echo -e "${BGREEN}[+] IP2ORG - INSTALLED${RESET}: ${TIME} seconds"
}

CERTINFO() {
    START_SPINNER "${BGREEN}CERTINFO${RESET}"
    gocl -i github.com/rix4uni/certinfo &>/dev/null

    if ! command -v certinfo &>/dev/null; then
        echo -e "${BRED}[x] CERTINFO - INSTALLATION FAILED${RESET}: ${TIME} seconds"
        STOP_SPINNER
        return
    fi

    STOP_SPINNER
    echo -e "${BGREEN}[+] CERTINFO - INSTALLED${RESET}: ${TIME} seconds"
}

XSSCHECKER() {
    START_SPINNER "${BGREEN}XSSCHECKER${RESET}"
    gocl -i github.com/rix4uni/xsschecker &>/dev/null

    if ! command -v xsschecker &>/dev/null; then
        echo -e "${BRED}[x] XSSCHECKER - INSTALLATION FAILED${RESET}: ${TIME} seconds"
        STOP_SPINNER
        return
    fi

    STOP_SPINNER
    echo -e "${BGREEN}[+] XSSCHECKER - INSTALLED${RESET}: ${TIME} seconds"
}

PORTMAP() {
    START_SPINNER "${BGREEN}PORTMAP${RESET}"
    gocl -i github.com/rix4uni/portmap &>/dev/null

    if ! command -v portmap &>/dev/null; then
        echo -e "${BRED}[x] PORTMAP - INSTALLATION FAILED${RESET}: ${TIME} seconds"
        STOP_SPINNER
        return
    fi

    STOP_SPINNER
    echo -e "${BGREEN}[+] PORTMAP - INSTALLED${RESET}: ${TIME} seconds"
}

PARAMFINDER() {
    START_SPINNER "${BGREEN}PARAMFINDER${RESET}"
    gocl -i github.com/rix4uni/paramfinder &>/dev/null

    if ! command -v paramfinder &>/dev/null; then
        echo -e "${BRED}[x] PARAMFINDER - INSTALLATION FAILED${RESET}: ${TIME} seconds"
        STOP_SPINNER
        return
    fi

    STOP_SPINNER
    echo -e "${BGREEN}[+] PARAMFINDER - INSTALLED${RESET}: ${TIME} seconds"
}

GXSS() {
    START_SPINNER "${BGREEN}GXSS${RESET}"
    gocl -i github.com/rix4uni/Gxss &>/dev/null

    if ! command -v Gxss &>/dev/null; then
        echo -e "${BRED}[x] GXSS - INSTALLATION FAILED${RESET}: ${TIME} seconds"
        STOP_SPINNER
        return
    fi

    STOP_SPINNER
    echo -e "${BGREEN}[+] GXSS - INSTALLED${RESET}: ${TIME} seconds"
}

MSARJUN() {
    START_SPINNER "${BGREEN}MSARJUN${RESET}"
    gocl -i github.com/rix4uni/msarjun &>/dev/null

    if ! command -v msarjun &>/dev/null; then
        echo -e "${BRED}[x] MSARJUN - INSTALLATION FAILED${RESET}: ${TIME} seconds"
        STOP_SPINNER
        return
    fi

    STOP_SPINNER
    echo -e "${BGREEN}[+] MSARJUN - INSTALLED${RESET}: ${TIME} seconds"
}

HAKRAWLER() {
    START_SPINNER "${BGREEN}HAKRAWLER${RESET}"
    gocl -i github.com/hakluke/hakrawler &>/dev/null

    if ! command -v hakrawler &>/dev/null; then
        echo -e "${BRED}[x] HAKRAWLER - INSTALLATION FAILED${RESET}: ${TIME} seconds"
        STOP_SPINNER
        return
    fi

    STOP_SPINNER
    echo -e "${BGREEN}[+] HAKRAWLER - INSTALLED${RESET}: ${TIME} seconds"
}

HAKREVDNS() {
    START_SPINNER "${BGREEN}HAKREVDNS${RESET}"
    gocl -i github.com/hakluke/hakrevdns &>/dev/null

    if ! command -v hakrevdns &>/dev/null; then
        echo -e "${BRED}[x] HAKREVDNS - INSTALLATION FAILED${RESET}: ${TIME} seconds"
        STOP_SPINNER
        return
    fi

    STOP_SPINNER
    echo -e "${BGREEN}[+] HAKREVDNS - INSTALLED${RESET}: ${TIME} seconds"
}

HAKLISTGEN() {
    START_SPINNER "${BGREEN}HAKLISTGEN${RESET}"
    gocl -i github.com/hakluke/haklistgen &>/dev/null

    if ! command -v haklistgen &>/dev/null; then
        echo -e "${BRED}[x] HAKLISTGEN - INSTALLATION FAILED${RESET}: ${TIME} seconds"
        STOP_SPINNER
        return
    fi

    STOP_SPINNER
    echo -e "${BGREEN}[+] HAKLISTGEN - INSTALLED${RESET}: ${TIME} seconds"
}

HAKORIGINFINDER() {
    START_SPINNER "${BGREEN}HAKORIGINFINDER${RESET}"
    gocl -i github.com/hakluke/hakoriginfinder &>/dev/null

    if ! command -v hakoriginfinder &>/dev/null; then
        echo -e "${BRED}[x] HAKORIGINFINDER - INSTALLATION FAILED${RESET}: ${TIME} seconds"
        STOP_SPINNER
        return
    fi

    STOP_SPINNER
    echo -e "${BGREEN}[+] HAKORIGINFINDER - INSTALLED${RESET}: ${TIME} seconds"
}

HAKCHECKURL() {
    START_SPINNER "${BGREEN}HAKCHECKURL${RESET}"
    gocl -i github.com/hakluke/hakcheckurl &>/dev/null

    if ! command -v hakcheckurl &>/dev/null; then
        echo -e "${BRED}[x] HAKCHECKURL - INSTALLATION FAILED${RESET}: ${TIME} seconds"
        STOP_SPINNER
        return
    fi

    STOP_SPINNER
    echo -e "${BGREEN}[+] HAKCHECKURL - INSTALLED${RESET}: ${TIME} seconds"
}

HAKTRAILS() {
    START_SPINNER "${BGREEN}HAKTRAILS${RESET}"
    gocl -i github.com/hakluke/haktrails &>/dev/null

    if ! command -v haktrails &>/dev/null; then
        echo -e "${BRED}[x] HAKTRAILS - INSTALLATION FAILED${RESET}: ${TIME} seconds"
        STOP_SPINNER
        return
    fi

    STOP_SPINNER
    echo -e "${BGREEN}[+] HAKTRAILS - INSTALLED${RESET}: ${TIME} seconds"
}

HAKIP2HOST() {
    START_SPINNER "${BGREEN}HAKIP2HOST${RESET}"
    gocl -i github.com/hakluke/hakip2host &>/dev/null

    if ! command -v hakip2host &>/dev/null; then
        echo -e "${BRED}[x] HAKIP2HOST - INSTALLATION FAILED${RESET}: ${TIME} seconds"
        STOP_SPINNER
        return
    fi

    STOP_SPINNER
    echo -e "${BGREEN}[+] HAKIP2HOST - INSTALLED${RESET}: ${TIME} seconds"
}

FFUF() {
    START_SPINNER "${BGREEN}FFUF${RESET}"
    gocl -i github.com/ffuf/ffuf &>/dev/null

    if ! command -v ffuf &>/dev/null; then
        echo -e "${BRED}[x] FFUF - INSTALLATION FAILED${RESET}: ${TIME} seconds"
        STOP_SPINNER
        return
    fi

    STOP_SPINNER
    echo -e "${BGREEN}[+] FFUF - INSTALLED${RESET}: ${TIME} seconds"
}

DIRSEARCH() {
    START_SPINNER "${BGREEN}DIRSEARCH${RESET}"
    pipx install --force git+https://github.com/maurosoria/dirsearch.git &>/dev/null

    if ! command -v dirsearch &>/dev/null; then
        echo -e "${BRED}[x] DIRSEARCH - INSTALLATION FAILED${RESET}: ${TIME} seconds"
        STOP_SPINNER
        return
    fi

    STOP_SPINNER
    echo -e "${BGREEN}[+] DIRSEARCH - INSTALLED${RESET}: ${TIME} seconds"
}

GOWITNESS() {
    START_SPINNER "${BGREEN}GOWITNESS${RESET}"
    gocl -i github.com/sensepost/gowitness &>/dev/null

    if ! command -v gowitness &>/dev/null; then
        echo -e "${BRED}[x] GOWITNESS - INSTALLATION FAILED${RESET}: ${TIME} seconds"
        STOP_SPINNER
        return
    fi

    STOP_SPINNER
    echo -e "${BGREEN}[+] GOWITNESS - INSTALLED${RESET}: ${TIME} seconds"
}

GITHUB_SUBDOMAINS() {
    START_SPINNER "${BGREEN}GITHUB_SUBDOMAINS${RESET}"
    gocl -i github.com/gwen001/github-subdomains &>/dev/null

    if ! command -v github-subdomains &>/dev/null; then
        echo -e "${BRED}[x] GITHUB_SUBDOMAINS - INSTALLATION FAILED${RESET}: ${TIME} seconds"
        STOP_SPINNER
        return
    fi

    STOP_SPINNER
    echo -e "${BGREEN}[+] GITHUB_SUBDOMAINS - INSTALLED${RESET}: ${TIME} seconds"
}

AMASS() {
    START_SPINNER "${BGREEN}AMASS${RESET}"
    go install -v github.com/owasp-amass/amass/v3/...@master &>/dev/null

    if ! command -v amass &>/dev/null; then
        echo -e "${BRED}[x] AMASS - INSTALLATION FAILED${RESET}: ${TIME} seconds"
        STOP_SPINNER
        return
    fi

    STOP_SPINNER
    echo -e "${BGREEN}[+] AMASS - INSTALLED${RESET}: ${TIME} seconds"
}

SHOSUBGO() {
    START_SPINNER "${BGREEN}SHOSUBGO${RESET}"
    gocl -i github.com/incogbyte/shosubgo &>/dev/null

    if ! command -v shosubgo &>/dev/null; then
        echo -e "${BRED}[x] SHOSUBGO - INSTALLATION FAILED${RESET}: ${TIME} seconds"
        STOP_SPINNER
        return
    fi

    STOP_SPINNER
    echo -e "${BGREEN}[+] SHOSUBGO - INSTALLED${RESET}: ${TIME} seconds"
}

GAU() {
    START_SPINNER "${BGREEN}GAU${RESET}"
    gocl -i github.com/lc/gau &>/dev/null

    if ! command -v gau &>/dev/null; then
        echo -e "${BRED}[x] GAU - INSTALLATION FAILED${RESET}: ${TIME} seconds"
        STOP_SPINNER
        return
    fi

    STOP_SPINNER
    echo -e "${BGREEN}[+] GAU - INSTALLED${RESET}: ${TIME} seconds"
}

SUBJS() {
    START_SPINNER "${BGREEN}SUBJS${RESET}"
    gocl -i github.com/lc/subjs &>/dev/null

    if ! command -v subjs &>/dev/null; then
        echo -e "${BRED}[x] SUBJS - INSTALLATION FAILED${RESET}: ${TIME} seconds"
        STOP_SPINNER
        return
    fi

    STOP_SPINNER
    echo -e "${BGREEN}[+] SUBJS - INSTALLED${RESET}: ${TIME} seconds"
}

GOSPIDER() {
    START_SPINNER "${BGREEN}GOSPIDER${RESET}"
    gocl -i github.com/jaeles-project/gospider &>/dev/null

    if ! command -v gospider &>/dev/null; then
        echo -e "${BRED}[x] GOSPIDER - INSTALLATION FAILED${RESET}: ${TIME} seconds"
        STOP_SPINNER
        return
    fi

    STOP_SPINNER
    echo -e "${BGREEN}[+] GOSPIDER - INSTALLED${RESET}: ${TIME} seconds"
}

JAELES() {
    START_SPINNER "${BGREEN}JAELES${RESET}"
    gocl -i github.com/jaeles-project/jaeles &>/dev/null

    if ! command -v jaeles &>/dev/null; then
        echo -e "${BRED}[x] JAELES - INSTALLATION FAILED${RESET}: ${TIME} seconds"
        STOP_SPINNER
        return
    fi

    STOP_SPINNER
    echo -e "${BGREEN}[+] JAELES - INSTALLED${RESET}: ${TIME} seconds"
}

GETJS() {
    START_SPINNER "${BGREEN}GETJS${RESET}"
    gocl -i github.com/003random/getJS &>/dev/null

    if ! command -v getJS &>/dev/null; then
        echo -e "${BRED}[x] GETJS - INSTALLATION FAILED${RESET}: ${TIME} seconds"
        STOP_SPINNER
        return
    fi

    STOP_SPINNER
    echo -e "${BGREEN}[+] GETJS - INSTALLED${RESET}: ${TIME} seconds"
}

JSLUICE() {
    START_SPINNER "${BGREEN}JSLUICE${RESET}"
    gocl -i github.com/BishopFox/jsluice &>/dev/null

    if ! command -v jsluice &>/dev/null; then
        echo -e "${BRED}[x] JSLUICE - INSTALLATION FAILED${RESET}: ${TIME} seconds"
        STOP_SPINNER
        return
    fi

    STOP_SPINNER
    echo -e "${BGREEN}[+] JSLUICE - INSTALLED${RESET}: ${TIME} seconds"
}

SHORTSCAN() {
    START_SPINNER "${BGREEN}SHORTSCAN${RESET}"
    gocl -i github.com/bitquark/shortscan &>/dev/null

    if ! command -v shortscan &>/dev/null; then
        echo -e "${BRED}[x] SHORTSCAN - INSTALLATION FAILED${RESET}: ${TIME} seconds"
        STOP_SPINNER
        return
    fi

    STOP_SPINNER
    echo -e "${BGREEN}[+] SHORTSCAN - INSTALLED${RESET}: ${TIME} seconds"
}

GUNGNIR() {
    START_SPINNER "${BGREEN}GUNGNIR${RESET}"
    gocl -i github.com/g0ldencybersec/gungnir &>/dev/null

    if ! command -v gungnir &>/dev/null; then
        echo -e "${BRED}[x] GUNGNIR - INSTALLATION FAILED${RESET}: ${TIME} seconds"
        STOP_SPINNER
        return
    fi

    STOP_SPINNER
    echo -e "${BGREEN}[+] GUNGNIR - INSTALLED${RESET}: ${TIME} seconds"
}

SNS() {
    START_SPINNER "${BGREEN}SNS${RESET}"
    gocl -i github.com/sw33tLie/sns &>/dev/null

    if ! command -v sns &>/dev/null; then
        echo -e "${BRED}[x] SNS - INSTALLATION FAILED${RESET}: ${TIME} seconds"
        STOP_SPINNER
        return
    fi

    STOP_SPINNER
    echo -e "${BGREEN}[+] SNS - INSTALLED${RESET}: ${TIME} seconds"
}

PUREDNS() {
    START_SPINNER "${BGREEN}PUREDNS${RESET}"
    gocl -i github.com/d3mondev/puredns &>/dev/null

    if ! command -v puredns &>/dev/null; then
        echo -e "${BRED}[x] PUREDNS - INSTALLATION FAILED${RESET}: ${TIME} seconds"
        STOP_SPINNER
        return
    fi

    STOP_SPINNER
    echo -e "${BGREEN}[+] PUREDNS - INSTALLED${RESET}: ${TIME} seconds"
}

DMUT() {
    START_SPINNER "${BGREEN}DMUT${RESET}"
    gocl -i github.com/bp0lr/dmut &>/dev/null

    if ! command -v dmut &>/dev/null; then
        echo -e "${BRED}[x] DMUT - INSTALLATION FAILED${RESET}: ${TIME} seconds"
        STOP_SPINNER
        return
    fi

    STOP_SPINNER
    echo -e "${BGREEN}[+] DMUT - INSTALLED${RESET}: ${TIME} seconds"
}

GOBUSTER() {
    START_SPINNER "${BGREEN}GOBUSTER${RESET}"
    gocl -i github.com/OJ/gobuster &>/dev/null

    if ! command -v gobuster &>/dev/null; then
        echo -e "${BRED}[x] GOBUSTER - INSTALLATION FAILED${RESET}: ${TIME} seconds"
        STOP_SPINNER
        return
    fi

    STOP_SPINNER
    echo -e "${BGREEN}[+] GOBUSTER - INSTALLED${RESET}: ${TIME} seconds"
}

SMAP() {
    START_SPINNER "${BGREEN}SMAP${RESET}"
    gocl -i github.com/s0md3v/smap &>/dev/null

    if ! command -v smap &>/dev/null; then
        echo -e "${BRED}[x] SMAP - INSTALLATION FAILED${RESET}: ${TIME} seconds"
        STOP_SPINNER
        return
    fi

    STOP_SPINNER
    echo -e "${BGREEN}[+] SMAP - INSTALLED${RESET}: ${TIME} seconds"
}

DALFOX() {
    START_SPINNER "${BGREEN}DALFOX${RESET}"
    gocl -i github.com/hahwul/dalfox &>/dev/null

    if ! command -v dalfox &>/dev/null; then
        echo -e "${BRED}[x] DALFOX - INSTALLATION FAILED${RESET}: ${TIME} seconds"
        STOP_SPINNER
        return
    fi

    STOP_SPINNER
    echo -e "${BGREEN}[+] DALFOX - INSTALLED${RESET}: ${TIME} seconds"
}

CERO() {
    START_SPINNER "${BGREEN}CERO${RESET}"
    gocl -i github.com/glebarez/cero &>/dev/null

    if ! command -v cero &>/dev/null; then
        echo -e "${BRED}[x] CERO - INSTALLATION FAILED${RESET}: ${TIME} seconds"
        STOP_SPINNER
        return
    fi

    STOP_SPINNER
    echo -e "${BGREEN}[+] CERO - INSTALLED${RESET}: ${TIME} seconds"
}

GOTATOR() {
    START_SPINNER "${BGREEN}GOTATOR${RESET}"
    gocl -i github.com/Josue87/gotator &>/dev/null

    if ! command -v gotator &>/dev/null; then
        echo -e "${BRED}[x] GOTATOR - INSTALLATION FAILED${RESET}: ${TIME} seconds"
        STOP_SPINNER
        return
    fi

    STOP_SPINNER
    echo -e "${BGREEN}[+] GOTATOR - INSTALLED${RESET}: ${TIME} seconds"
}

ANALYTICSRELATIONSHIPS() {
    START_SPINNER "${BGREEN}ANALYTICSRELATIONSHIPS${RESET}"
    gocl -i github.com/Josue87/analyticsrelationships &>/dev/null

    if ! command -v analyticsrelationships &>/dev/null; then
        echo -e "${BRED}[x] ANALYTICSRELATIONSHIPS - INSTALLATION FAILED${RESET}: ${TIME} seconds"
        STOP_SPINNER
        return
    fi

    STOP_SPINNER
    echo -e "${BGREEN}[+] ANALYTICSRELATIONSHIPS - INSTALLED${RESET}: ${TIME} seconds"
}

MANTRA() {
    START_SPINNER "${BGREEN}MANTRA${RESET}"
    gocl -i github.com/MrEmpy/mantra &>/dev/null

    if ! command -v mantra &>/dev/null; then
        echo -e "${BRED}[x] MANTRA - INSTALLATION FAILED${RESET}: ${TIME} seconds"
        STOP_SPINNER
        return
    fi

    STOP_SPINNER
    echo -e "${BGREEN}[+] MANTRA - INSTALLED${RESET}: ${TIME} seconds"
}

CRT() {
    START_SPINNER "${BGREEN}CRT${RESET}"
    gocl -i github.com/cemulus/crt &>/dev/null

    if ! command -v crt &>/dev/null; then
        echo -e "${BRED}[x] CRT - INSTALLATION FAILED${RESET}: ${TIME} seconds"
        STOP_SPINNER
        return
    fi

    STOP_SPINNER
    echo -e "${BGREEN}[+] CRT - INSTALLED${RESET}: ${TIME} seconds"
}

URLGRAB() {
    START_SPINNER "${BGREEN}URLGRAB${RESET}"
    gocl -i github.com/iamstoxe/urlgrab &>/dev/null

    if ! command -v urlgrab &>/dev/null; then
        echo -e "${BRED}[x] URLGRAB - INSTALLATION FAILED${RESET}: ${TIME} seconds"
        STOP_SPINNER
        return
    fi

    STOP_SPINNER
    echo -e "${BGREEN}[+] URLGRAB - INSTALLED${RESET}: ${TIME} seconds"
}

GOLINKFINDER() {
    START_SPINNER "${BGREEN}GOLINKFINDER${RESET}"
    gocl -i github.com/rix4uni/GoLinkFinder &>/dev/null

    if ! command -v GoLinkFinder &>/dev/null; then
        echo -e "${BRED}[x] GOLINKFINDER - INSTALLATION FAILED${RESET}: ${TIME} seconds"
        STOP_SPINNER
        return
    fi

    STOP_SPINNER
    echo -e "${BGREEN}[+] GOLINKFINDER - INSTALLED${RESET}: ${TIME} seconds"
}

LINX() {
    START_SPINNER "${BGREEN}LINX${RESET}"
    gocl -i github.com/riza/linx &>/dev/null

    if ! command -v linx &>/dev/null; then
        echo -e "${BRED}[x] LINX - INSTALLATION FAILED${RESET}: ${TIME} seconds"
        STOP_SPINNER
        return
    fi

    STOP_SPINNER
    echo -e "${BGREEN}[+] LINX - INSTALLED${RESET}: ${TIME} seconds"
}

KXSS() {
    START_SPINNER "${BGREEN}KXSS${RESET}"
    gocl -i github.com/Emoe/kxss &>/dev/null

    if ! command -v kxss &>/dev/null; then
        echo -e "${BRED}[x] KXSS - INSTALLATION FAILED${RESET}: ${TIME} seconds"
        STOP_SPINNER
        return
    fi

    STOP_SPINNER
    echo -e "${BGREEN}[+] KXSS - INSTALLED${RESET}: ${TIME} seconds"
}

GALER() {
    START_SPINNER "${BGREEN}GALER${RESET}"
    gocl -i github.com/dwisiswant0/galer &>/dev/null

    if ! command -v galer &>/dev/null; then
        echo -e "${BRED}[x] GALER - INSTALLATION FAILED${RESET}: ${TIME} seconds"
        STOP_SPINNER
        return
    fi

    STOP_SPINNER
    echo -e "${BGREEN}[+] GALER - INSTALLED${RESET}: ${TIME} seconds"
}

JSFINDER() {
    START_SPINNER "${BGREEN}JSFINDER${RESET}"
    gocl -i github.com/kacakb/jsfinder &>/dev/null

    if ! command -v jsfinder &>/dev/null; then
        echo -e "${BRED}[x] JSFINDER - INSTALLATION FAILED${RESET}: ${TIME} seconds"
        STOP_SPINNER
        return
    fi

    STOP_SPINNER
    echo -e "${BGREEN}[+] JSFINDER - INSTALLED${RESET}: ${TIME} seconds"
}

PATHFINDER() {
    START_SPINNER "${BGREEN}PATHFINDER${RESET}"
    gocl -i github.com/Print3M/pathfinder &>/dev/null

    if ! command -v pathfinder &>/dev/null; then
        echo -e "${BRED}[x] PATHFINDER - INSTALLATION FAILED${RESET}: ${TIME} seconds"
        STOP_SPINNER
        return
    fi

    STOP_SPINNER
    echo -e "${BGREEN}[+] PATHFINDER - INSTALLED${RESET}: ${TIME} seconds"
}

TRUFFLEHOG() {
    START_SPINNER "${BGREEN}TRUFFLEHOG${RESET}"
    gocl -i github.com/trufflesecurity/trufflehog &>/dev/null

    if ! command -v trufflehog &>/dev/null; then
        echo -e "${BRED}[x] TRUFFLEHOG - INSTALLATION FAILED${RESET}: ${TIME} seconds"
        STOP_SPINNER
        return
    fi

    STOP_SPINNER
    echo -e "${BGREEN}[+] TRUFFLEHOG - INSTALLED${RESET}: ${TIME} seconds"
}

JSHUNTER() {
    START_SPINNER "${BGREEN}JSHUNTER${RESET}"
    gocl -i github.com/cc1a2b/JShunter &>/dev/null

    if ! command -v jshunter &>/dev/null; then
        echo -e "${BRED}[x] JSHUNTER - INSTALLATION FAILED${RESET}: ${TIME} seconds"
        STOP_SPINNER
        return
    fi

    STOP_SPINNER
    echo -e "${BGREEN}[+] JSHUNTER - INSTALLED${RESET}: ${TIME} seconds"
}

PPFUZZ() {
    START_SPINNER "${BGREEN}PPFUZZ${RESET}"
    # Taking too much time/ram to build
    # git clone https://github.com/dwisiswant0/ppfuzz.git --depth 1 &>/dev/null
    # cd ppfuzz
    # cargo build --release --jobs 1 &>/dev/null
    # mv target/release/ppfuzz /usr/local/bin/
    # cd ..
    # rm -rf ppfuzz

    wget -q https://github.com/dwisiswant0/ppfuzz/releases/download/v1.0.2/ppfuzz-v1.0.2-x86_64-unknown-linux-musl.tar.gz
    tar -xzf ppfuzz-v1.0.2-x86_64-unknown-linux-musl.tar.gz &>/dev/null
    mv ppfuzz /usr/local/bin/
    rm -rf ppfuzz-v1.0.2-x86_64-unknown-linux-musl.tar.gz

    if ! command -v ppfuzz &>/dev/null; then
        echo -e "${BRED}[x] PPFUZZ - INSTALLATION FAILED${RESET}: ${TIME} seconds"
        STOP_SPINNER
        return
    fi

    STOP_SPINNER
    echo -e "${BGREEN}[+] PPFUZZ - INSTALLED${RESET}: ${TIME} seconds"
}

BRUTESPRAY() {
    START_SPINNER "${BGREEN}BRUTESPRAY${RESET}"
    gocl -i github.com/x90skysn3k/brutespray &>/dev/null

    if ! command -v brutespray &>/dev/null; then
        echo -e "${BRED}[x] BRUTESPRAY - INSTALLATION FAILED${RESET}: ${TIME} seconds"
        STOP_SPINNER
        return
    fi

    STOP_SPINNER
    echo -e "${BGREEN}[+] BRUTESPRAY - INSTALLED${RESET}: ${TIME} seconds"
}

LINKINSPECTOR() {
    START_SPINNER "${BGREEN}LINKINSPECTOR${RESET}"
    gocl -i github.com/rix4uni/linkinspector &>/dev/null

    if ! command -v linkinspector &>/dev/null; then
        echo -e "${BRED}[x] LINKINSPECTOR - INSTALLATION FAILED${RESET}: ${TIME} seconds"
        STOP_SPINNER
        return
    fi

    STOP_SPINNER
    echo -e "${BGREEN}[+] LINKINSPECTOR - INSTALLED${RESET}: ${TIME} seconds"
}

WORDGEN() {
    START_SPINNER "${BGREEN}WORDGEN${RESET}"
    gocl -i github.com/rix4uni/wordgen &>/dev/null

    if ! command -v wordgen &>/dev/null; then
        echo -e "${BRED}[x] WORDGEN - INSTALLATION FAILED${RESET}: ${TIME} seconds"
        STOP_SPINNER
        return
    fi

    STOP_SPINNER
    echo -e "${BGREEN}[+] WORDGEN - INSTALLED${RESET}: ${TIME} seconds"
}

FUZZULI() {
    START_SPINNER "${BGREEN}FUZZULI${RESET}"
    gocl -i github.com/musana/fuzzuli &>/dev/null

    if ! command -v fuzzuli &>/dev/null; then
        echo -e "${BRED}[x] FUZZULI - INSTALLATION FAILED${RESET}: ${TIME} seconds"
        STOP_SPINNER
        return
    fi

    STOP_SPINNER
    echo -e "${BGREEN}[+] FUZZULI - INSTALLED${RESET}: ${TIME} seconds"
}

PYXSS() {
    START_SPINNER "${BGREEN}PYXSS${RESET}"
    pipx install --force git+https://github.com/rix4uni/pyxss.git &>/dev/null

    if ! command -v pyxss &>/dev/null; then
        echo -e "${BRED}[x] PYXSS - INSTALLATION FAILED${RESET}: ${TIME} seconds"
        STOP_SPINNER
        return
    fi

    STOP_SPINNER
    echo -e "${BGREEN}[+] PYXSS - INSTALLED${RESET}: ${TIME} seconds"
}

ARINRANGE() {
    START_SPINNER "${BGREEN}ARINRANGE${RESET}"
    pipx install --force git+https://github.com/rix4uni/arinrange.git &>/dev/null

    if ! command -v arinrange &>/dev/null; then
        echo -e "${BRED}[x] ARINRANGE - INSTALLATION FAILED${RESET}: ${TIME} seconds"
        STOP_SPINNER
        return
    fi

    STOP_SPINNER
    echo -e "${BGREEN}[+] ARINRANGE - INSTALLED${RESET}: ${TIME} seconds"
}

BUILTWITHSUBS() {
    START_SPINNER "${BGREEN}BUILTWITHSUBS${RESET}"
    pipx install --force git+https://github.com/rix4uni/BUILTWITHSUBS.git &>/dev/null

    if ! command -v builtwithsubs &>/dev/null; then
        echo -e "${BRED}[x] BUILTWITHSUBS - INSTALLATION FAILED${RESET}: ${TIME} seconds"
        STOP_SPINNER
        return
    fi

    STOP_SPINNER
    echo -e "${BGREEN}[+] BUILTWITHSUBS - INSTALLED${RESET}: ${TIME} seconds"
}

GOOP() {
    START_SPINNER "${BGREEN}GOOP${RESET}"
    gocl -i github.com/nyancrimew/goop &>/dev/null

    if ! command -v goop &>/dev/null; then
        echo -e "${BRED}[x] GOOP - INSTALLATION FAILED${RESET}: ${TIME} seconds"
        STOP_SPINNER
        return
    fi

    STOP_SPINNER
    echo -e "${BGREEN}[+] GOOP - INSTALLED${RESET}: ${TIME} seconds"
}

COMMIX() {
    START_SPINNER "${BGREEN}COMMIX${RESET}"
    git clone https://github.com/commixproject/commix.git --depth 1 &>/dev/null
    cd commix
    sed -i "s/version='[0-9]\+\.[0-9]\+[^']*'/version='4.0'/g" setup.py
    python3 setup.py install &>/dev/null
    cd ..
    rm -rf commix

    if ! command -v commix &>/dev/null; then
        echo -e "${BRED}[x] COMMIX - INSTALLATION FAILED${RESET}: ${TIME} seconds"
        STOP_SPINNER
        return
    fi

    STOP_SPINNER
    echo -e "${BGREEN}[+] COMMIX - INSTALLED${RESET}: ${TIME} seconds"
}

PVREPLACE() {
    START_SPINNER "${BGREEN}PVREPLACE${RESET}"
    gocl -i github.com/rix4uni/pvreplace &>/dev/null

    if ! command -v pvreplace &>/dev/null; then
        echo -e "${BRED}[x] PVREPLACE - INSTALLATION FAILED${RESET}: ${TIME} seconds"
        STOP_SPINNER
        return
    fi

    STOP_SPINNER
    echo -e "${BGREEN}[+] PVREPLACE - INSTALLED${RESET}: ${TIME} seconds"
}

SSB() {
    START_SPINNER "${BGREEN}SSB${RESET}"
    gocl -i github.com/pwnesia/ssb &>/dev/null

    if ! command -v ssb &>/dev/null; then
        echo -e "${BRED}[x] SSB - INSTALLATION FAILED${RESET}: ${TIME} seconds"
        STOP_SPINNER
        return
    fi

    STOP_SPINNER
    echo -e "${BGREEN}[+] SSB - INSTALLED${RESET}: ${TIME} seconds"
}

FTPX() {
    START_SPINNER "${BGREEN}FTPX${RESET}"
    gocl -i github.com/rix4uni/ftpx &>/dev/null

    if ! command -v ftpx &>/dev/null; then
        echo -e "${BRED}[x] FTPX - INSTALLATION FAILED${RESET}: ${TIME} seconds"
        STOP_SPINNER
        return
    fi

    STOP_SPINNER
    echo -e "${BGREEN}[+] FTPX - INSTALLED${RESET}: ${TIME} seconds"
}

DNSTAKE() {
    START_SPINNER "${BGREEN}DNSTAKE${RESET}"
    gocl -i github.com/pwnesia/dnstake &>/dev/null

    if ! command -v dnstake &>/dev/null; then
        echo -e "${BRED}[x] DNSTAKE - INSTALLATION FAILED${RESET}: ${TIME} seconds"
        STOP_SPINNER
        return
    fi

    STOP_SPINNER
    echo -e "${BGREEN}[+] DNSTAKE - INSTALLED${RESET}: ${TIME} seconds"
}

MX_TAKEOVER() {
    START_SPINNER "${BGREEN}MX_TAKEOVER${RESET}"
    gocl -i github.com/musana/mx-takeover &>/dev/null

    if ! command -v mx-takeover &>/dev/null; then
        echo -e "${BRED}[x] MX_TAKEOVER - INSTALLATION FAILED${RESET}: ${TIME} seconds"
        STOP_SPINNER
        return
    fi

    STOP_SPINNER
    echo -e "${BGREEN}[+] MX_TAKEOVER - INSTALLED${RESET}: ${TIME} seconds"
}

SUBZY() {
    START_SPINNER "${BGREEN}SUBZY${RESET}"
    gocl -i github.com/rix4uni/subzy &>/dev/null

    if ! command -v subzy &>/dev/null; then
        echo -e "${BRED}[x] SUBZY - INSTALLATION FAILED${RESET}: ${TIME} seconds"
        STOP_SPINNER
        return
    fi

    STOP_SPINNER
    echo -e "${BGREEN}[+] SUBZY - INSTALLED${RESET}: ${TIME} seconds"
}

URLDEDUPE() {
    START_SPINNER "${BGREEN}URLDEDUPE${RESET}"
    git clone https://github.com/ameenmaali/urldedupe.git --depth 1 &>/dev/null
    cd urldedupe
    cmake CMakeLists.txt &>/dev/null
    make &>/dev/null
    mv urldedupe /usr/local/bin/
    cd ..
    rm -rf urldedupe

    if ! command -v urldedupe &>/dev/null; then
        echo -e "${BRED}[x] URLDEDUPE - INSTALLATION FAILED${RESET}: ${TIME} seconds"
        STOP_SPINNER
        return
    fi

    STOP_SPINNER
    echo -e "${BGREEN}[+] URLDEDUPE - INSTALLED${RESET}: ${TIME} seconds"
}

TIMELIMITX() {
    START_SPINNER "${BGREEN}TIMELIMITX${RESET}"
    gocl -i github.com/rix4uni/timelimitx &>/dev/null

    if ! command -v timelimitx &>/dev/null; then
        echo -e "${BRED}[x] TIMELIMITX - INSTALLATION FAILED${RESET}: ${TIME} seconds"
        STOP_SPINNER
        return
    fi

    STOP_SPINNER
    echo -e "${BGREEN}[+] TIMELIMITX - INSTALLED${RESET}: ${TIME} seconds"
}

SOURCEMAPPER() {
    START_SPINNER "${BGREEN}SOURCEMAPPER${RESET}"
    gocl -i github.com/denandz/sourcemapper &>/dev/null

    if ! command -v sourcemapper &>/dev/null; then
        echo -e "${BRED}[x] SOURCEMAPPER - INSTALLATION FAILED${RESET}: ${TIME} seconds"
        STOP_SPINNER
        return
    fi

    STOP_SPINNER
    echo -e "${BGREEN}[+] SOURCEMAPPER - INSTALLED${RESET}: ${TIME} seconds"
}

JSCRAWLER() {
    START_SPINNER "${BGREEN}JSCRAWLER${RESET}"
    pipx install --force git+https://github.com/rix4uni/jscrawler.git &>/dev/null

    if ! command -v jscrawler &>/dev/null; then
        echo -e "${BRED}[x] JSCRAWLER - INSTALLATION FAILED${RESET}: ${TIME} seconds"
        STOP_SPINNER
        return
    fi

    STOP_SPINNER
    echo -e "${BGREEN}[+] JSCRAWLER - INSTALLED${RESET}: ${TIME} seconds"
}

GORKER() {
    START_SPINNER "${BGREEN}GORKER${RESET}"
    pipx install --force git+https://github.com/rix4uni/gorker.git &>/dev/null

    if ! command -v gorker &>/dev/null; then
        echo -e "${BRED}[x] GORKER - INSTALLATION FAILED${RESET}: ${TIME} seconds"
        STOP_SPINNER
        return
    fi

    STOP_SPINNER
    echo -e "${BGREEN}[+] GORKER - INSTALLED${RESET}: ${TIME} seconds"
}

ROBOTXT() {
    START_SPINNER "${BGREEN}ROBOTXT${RESET}"
    gocl -i github.com/rix4uni/robotxt &>/dev/null

    if ! command -v robotxt &>/dev/null; then
        echo -e "${BRED}[x] ROBOTXT - INSTALLATION FAILED${RESET}: ${TIME} seconds"
        STOP_SPINNER
        return
    fi

    STOP_SPINNER
    echo -e "${BGREEN}[+] ROBOTXT - INSTALLED${RESET}: ${TIME} seconds"
}

ROBOXTRACTOR() {
    START_SPINNER "${BGREEN}ROBOXTRACTOR${RESET}"
    gocl -i github.com/Josue87/roboxtractor &>/dev/null

    if ! command -v roboxtractor &>/dev/null; then
        echo -e "${BRED}[x] ROBOXTRACTOR - INSTALLATION FAILED${RESET}: ${TIME} seconds"
        STOP_SPINNER
        return
    fi

    STOP_SPINNER
    echo -e "${BGREEN}[+] ROBOXTRACTOR - INSTALLED${RESET}: ${TIME} seconds"
}

PATHCRAWLER() {
    START_SPINNER "${BGREEN}PATHCRAWLER${RESET}"
    gocl -i github.com/rix4uni/pathcrawler &>/dev/null

    if ! command -v pathcrawler &>/dev/null; then
        echo -e "${BRED}[x] PATHCRAWLER - INSTALLATION FAILED${RESET}: ${TIME} seconds"
        STOP_SPINNER
        return
    fi

    STOP_SPINNER
    echo -e "${BGREEN}[+] PATHCRAWLER - INSTALLED${RESET}: ${TIME} seconds"
}

CRAWLEY() {
    START_SPINNER "${BGREEN}CRAWLEY${RESET}"
    gocl -i github.com/s0rg/crawley &>/dev/null

    if ! command -v crawley &>/dev/null; then
        echo -e "${BRED}[x] CRAWLEY - INSTALLATION FAILED${RESET}: ${TIME} seconds"
        STOP_SPINNER
        return
    fi

    STOP_SPINNER
    echo -e "${BGREEN}[+] CRAWLEY - INSTALLED${RESET}: ${TIME} seconds"
}

XCRAWL3R() {
    START_SPINNER "${BGREEN}XCRAWL3R${RESET}"
    gocl -i github.com/hueristiq/xcrawl3r &>/dev/null

    if ! command -v xcrawl3r &>/dev/null; then
        echo -e "${BRED}[x] XCRAWL3R - INSTALLATION FAILED${RESET}: ${TIME} seconds"
        STOP_SPINNER
        return
    fi

    STOP_SPINNER
    echo -e "${BGREEN}[+] XCRAWL3R - INSTALLED${RESET}: ${TIME} seconds"
}

XURLFIND3R() {
    START_SPINNER "${BGREEN}XURLFIND3R${RESET}"
    gocl -i github.com/hueristiq/xurlfind3r &>/dev/null

    if ! command -v xurlfind3r &>/dev/null; then
        echo -e "${BRED}[x] XURLFIND3R - INSTALLATION FAILED${RESET}: ${TIME} seconds"
        STOP_SPINNER
        return
    fi

    STOP_SPINNER
    echo -e "${BGREEN}[+] XURLFIND3R - INSTALLED${RESET}: ${TIME} seconds"
}

GITHUB_ENDPOINTS() {
    START_SPINNER "${BGREEN}GITHUB_ENDPOINTS${RESET}"
    gocl -i github.com/gwen001/github-endpoints &>/dev/null

    if ! command -v github-endpoints &>/dev/null; then
        echo -e "${BRED}[x] GITHUB_ENDPOINTS - INSTALLATION FAILED${RESET}: ${TIME} seconds"
        STOP_SPINNER
        return
    fi

    STOP_SPINNER
    echo -e "${BGREEN}[+] GITHUB_ENDPOINTS - INSTALLED${RESET}: ${TIME} seconds"
}

URLFINDER() {
    START_SPINNER "${BGREEN}URLFINDER${RESET}"
    gocl -i github.com/projectdiscovery/urlfinder &>/dev/null

    if ! command -v urlfinder &>/dev/null; then
        echo -e "${BRED}[x] URLFINDER - INSTALLATION FAILED${RESET}: ${TIME} seconds"
        STOP_SPINNER
        return
    fi

    STOP_SPINNER
    echo -e "${BGREEN}[+] URLFINDER - INSTALLED${RESET}: ${TIME} seconds"
}

CARIDDI() {
    START_SPINNER "${BGREEN}CARIDDI${RESET}"
    gocl -i github.com/edoardottt/cariddi &>/dev/null

    if ! command -v cariddi &>/dev/null; then
        echo -e "${BRED}[x] CARIDDI - INSTALLATION FAILED${RESET}: ${TIME} seconds"
        STOP_SPINNER
        return
    fi

    STOP_SPINNER
    echo -e "${BGREEN}[+] CARIDDI - INSTALLED${RESET}: ${TIME} seconds"
}

UFORALL() {
    START_SPINNER "${BGREEN}UFORALL${RESET}"
    gocl -i github.com/rix4uni/uforall &>/dev/null

    if ! command -v uforall &>/dev/null; then
        echo -e "${BRED}[x] UFORALL - INSTALLATION FAILED${RESET}: ${TIME} seconds"
        STOP_SPINNER
        return
    fi

    STOP_SPINNER
    echo -e "${BGREEN}[+] UFORALL - INSTALLED${RESET}: ${TIME} seconds"
}

EMAILFINDER() {
    START_SPINNER "${BGREEN}EMAILFINDER${RESET}"
    gocl -i github.com/rix4uni/emailfinder &>/dev/null

    if ! command -v emailfinder &>/dev/null; then
        echo -e "${BRED}[x] EMAILFINDER - INSTALLATION FAILED${RESET}: ${TIME} seconds"
        STOP_SPINNER
        return
    fi

    STOP_SPINNER
    echo -e "${BGREEN}[+] EMAILFINDER - INSTALLED${RESET}: ${TIME} seconds"
}

FAVIRECON() {
    START_SPINNER "${BGREEN}FAVIRECON${RESET}"
    gocl -i github.com/edoardottt/favirecon &>/dev/null

    if ! command -v favirecon &>/dev/null; then
        echo -e "${BRED}[x] FAVIRECON - INSTALLATION FAILED${RESET}: ${TIME} seconds"
        STOP_SPINNER
        return
    fi

    STOP_SPINNER
    echo -e "${BGREEN}[+] FAVIRECON - INSTALLED${RESET}: ${TIME} seconds"
}

FAVINFO() {
    START_SPINNER "${BGREEN}FAVINFO${RESET}"
    gocl -i github.com/rix4uni/favinfo &>/dev/null

    if ! command -v favinfo &>/dev/null; then
        echo -e "${BRED}[x] FAVINFO - INSTALLATION FAILED${RESET}: ${TIME} seconds"
        STOP_SPINNER
        return
    fi

    STOP_SPINNER
    echo -e "${BGREEN}[+] FAVINFO - INSTALLED${RESET}: ${TIME} seconds"
}

DLEVEL() {
    START_SPINNER "${BGREEN}DLEVEL${RESET}"
    gocl -i github.com/rix4uni/dlevel &>/dev/null

    if ! command -v dlevel &>/dev/null; then
        echo -e "${BRED}[x] DLEVEL - INSTALLATION FAILED${RESET}: ${TIME} seconds"
        STOP_SPINNER
        return
    fi

    STOP_SPINNER
    echo -e "${BGREEN}[+] DLEVEL - INSTALLED${RESET}: ${TIME} seconds"
}

SUBDOMAINFUZZ() {
    START_SPINNER "${BGREEN}SUBDOMAINFUZZ${RESET}"
    gocl -i github.com/rix4uni/subdomainfuzz &>/dev/null

    if ! command -v subdomainfuzz &>/dev/null; then
        echo -e "${BRED}[x] SUBDOMAINFUZZ - INSTALLATION FAILED${RESET}: ${TIME} seconds"
        STOP_SPINNER
        return
    fi

    STOP_SPINNER
    echo -e "${BGREEN}[+] SUBDOMAINFUZZ - INSTALLED${RESET}: ${TIME} seconds"
}

GOURLEX() {
    START_SPINNER "${BGREEN}GOURLEX${RESET}"
    gocl -i github.com/trap-bytes/gourlex &>/dev/null

    if ! command -v gourlex &>/dev/null; then
        echo -e "${BRED}[x] GOURLEX - INSTALLATION FAILED${RESET}: ${TIME} seconds"
        STOP_SPINNER
        return
    fi

    STOP_SPINNER
    echo -e "${BGREEN}[+] GOURLEX - INSTALLED${RESET}: ${TIME} seconds"
}

CSPFINDER() {
    START_SPINNER "${BGREEN}CSPFINDER${RESET}"
    gocl -i github.com/rix4uni/cspfinder &>/dev/null

    if ! command -v cspfinder &>/dev/null; then
        echo -e "${BRED}[x] CSPFINDER - INSTALLATION FAILED${RESET}: ${TIME} seconds"
        STOP_SPINNER
        return
    fi

    STOP_SPINNER
    echo -e "${BGREEN}[+] CSPFINDER - INSTALLED${RESET}: ${TIME} seconds"
}

CSPRECON() {
    START_SPINNER "${BGREEN}CSPRECON${RESET}"
    gocl -i github.com/edoardottt/csprecon &>/dev/null

    if ! command -v csprecon &>/dev/null; then
        echo -e "${BRED}[x] CSPRECON - INSTALLATION FAILED${RESET}: ${TIME} seconds"
        STOP_SPINNER
        return
    fi

    STOP_SPINNER
    echo -e "${BGREEN}[+] CSPRECON - INSTALLED${RESET}: ${TIME} seconds"
}

GITREPOENUM() {
    START_SPINNER "${BGREEN}GITREPOENUM${RESET}"
    gocl -i github.com/rix4uni/gitrepoenum &>/dev/null

    if ! command -v gitrepoenum &>/dev/null; then
        echo -e "${BRED}[x] GITREPOENUM - INSTALLATION FAILED${RESET}: ${TIME} seconds"
        STOP_SPINNER
        return
    fi

    STOP_SPINNER
    echo -e "${BGREEN}[+] GITREPOENUM - INSTALLED${RESET}: ${TIME} seconds"
}

S3SCANNER() {
    START_SPINNER "${BGREEN}S3SCANNER${RESET}"
    go install -v github.com/sa7mon/s3scanner@latest &>/dev/null

    if ! command -v s3scanner &>/dev/null; then
        echo -e "${BRED}[x] S3SCANNER - INSTALLATION FAILED${RESET}: ${TIME} seconds"
        STOP_SPINNER
        return
    fi

    STOP_SPINNER
    echo -e "${BGREEN}[+] S3SCANNER - INSTALLED${RESET}: ${TIME} seconds"
}

SPK() {
    START_SPINNER "${BGREEN}SPK${RESET}"
    gocl -i github.com/dhn/spk &>/dev/null

    if ! command -v spk &>/dev/null; then
        echo -e "${BRED}[x] SPK - INSTALLATION FAILED${RESET}: ${TIME} seconds"
        STOP_SPINNER
        return
    fi

    STOP_SPINNER
    echo -e "${BGREEN}[+] SPK - INSTALLED${RESET}: ${TIME} seconds"
}

RIPGEN() {
    START_SPINNER "${BGREEN}RIPGEN${RESET}"
    cargo install ripgen &>/dev/null

    if ! command -v ripgen &>/dev/null; then
        echo -e "${BRED}[x] RIPGEN - INSTALLATION FAILED${RESET}: ${TIME} seconds"
        STOP_SPINNER
        return
    fi

    STOP_SPINNER
    echo -e "${BGREEN}[+] RIPGEN - INSTALLED${RESET}: ${TIME} seconds"
}

GOALTDNS() {
    START_SPINNER "${BGREEN}GOALTDNS${RESET}"
    go install -v github.com/subfinder/goaltdns@latest &>/dev/null

    if ! command -v goaltdns &>/dev/null; then
        echo -e "${BRED}[x] GOALTDNS - INSTALLATION FAILED${RESET}: ${TIME} seconds"
        STOP_SPINNER
        return
    fi

    STOP_SPINNER
    echo -e "${BGREEN}[+] GOALTDNS - INSTALLED${RESET}: ${TIME} seconds"
}

DNSGEN() {
    START_SPINNER "${BGREEN}DNSGEN${RESET}"
    python3 -m pip install dnsgen --no-cache-dir &>/dev/null

    if ! command -v dnsgen &>/dev/null; then
        echo -e "${BRED}[x] DNSGEN - INSTALLATION FAILED${RESET}: ${TIME} seconds"
        STOP_SPINNER
        return
    fi

    STOP_SPINNER
    echo -e "${BGREEN}[+] DNSGEN - INSTALLED${RESET}: ${TIME} seconds"
}

RCERT() {
    START_SPINNER "${BGREEN}RCERT${RESET}"
    git clone https://github.com/rix4uni/rcert.git --depth 1 &>/dev/null
    cd rcert
    chmod +x rcert
    mv rcert /usr/bin/
    cd ..
    rm -rf rcert

    if ! command -v rcert &>/dev/null; then
        echo -e "${BRED}[x] RCERT - INSTALLATION FAILED${RESET}: ${TIME} seconds"
        STOP_SPINNER
        return
    fi

    STOP_SPINNER
    echo -e "${BGREEN}[+] RCERT - INSTALLED${RESET}: ${TIME} seconds"
}

IPFINDER() {
    START_SPINNER "${BGREEN}IPFINDER${RESET}"
    gocl -i github.com/rix4uni/ipfinder &>/dev/null

    if ! command -v ipfinder &>/dev/null; then
        echo -e "${BRED}[x] IPFINDER - INSTALLATION FAILED${RESET}: ${TIME} seconds"
        STOP_SPINNER
        return
    fi

    STOP_SPINNER
    echo -e "${BGREEN}[+] IPFINDER - INSTALLED${RESET}: ${TIME} seconds"
}


# CONFIGS
CONFIGS() {
    START_SPINNER "${BGREEN}CONFIGS${RESET}"
    mkdir -p ~/.config/favinfo && curl -s "https://raw.githubusercontent.com/rix4uni/favinfo/refs/heads/main/fingerprint.json" >> ~/.config/favinfo/fingerprint.json
    mkdir -p ~/.config/waymore && curl -s "https://raw.githubusercontent.com/xnl-h4ck3r/waymore/refs/heads/main/config.yml" >> ~/.config/waymore/config.yml
    mkdir -p ~/.config/xnLinkFinder && curl -s "https://raw.githubusercontent.com/xnl-h4ck3r/xnLinkFinder/refs/heads/main/config.yml" >> ~/.config/xnLinkFinder/config.yml
    mkdir -p ~/.config/gitrepoenum && curl -s "https://raw.githubusercontent.com/rix4uni/gitrepoenum/refs/heads/main/config/config.yaml" >> ~/.config/gitrepoenum/config.yml
    mkdir -p ~/.config/chaos && touch ~/.config/chaos/chaos-api.txt
    mkdir -p ~/.config/shosubgo && touch ~/.config/shosubgo/shosubgo-api.txt

    STOP_SPINNER
    echo -e "${BGREEN}[+] CONFIGS - INSTALLED${RESET}: ${TIME} seconds"
}


# SOME DATA
TRICKESTCLOUD() {
    START_SPINNER "${BGREEN}TRICKESTCLOUD${RESET}"
    wget -q -O wordlists/trickestcloud.zip https://github.com/trickest/cloud/archive/refs/heads/main.zip
    unzip -q wordlists/trickestcloud.zip -d wordlists
    mv wordlists/cloud-main wordlists/trickestcloud
    cat wordlists/trickestcloud/ssl/ssl*.csv | cut -d"," -f2,7 | tr "|" "\n" | tr "," "\n" | sed 's/"//g' | unew -el -i -t -q wordlists/trickestcloud_ssl.txt

    rm -rf wordlists/trickestcloud.zip wordlists/trickestcloud

    STOP_SPINNER
    echo -e "${BGREEN}[+] TRICKESTCLOUD - INSTALLED${RESET}: ${TIME} seconds"
}


# WORDLISTS
WORDLISTS() {
    START_SPINNER "${BGREEN}WORDLISTS${RESET}"
    curl -s "https://wordlists-cdn.assetnote.io/data/manual/best-dns-wordlist.txt" | unew -el -t -q wordlists/best-dns-wordlist.txt
    curl -s "https://wordlists-cdn.assetnote.io/data/manual/2m-subdomains.txt" | unew -el -t -q wordlists/2m-subdomains.txt
    curl -s "https://wordlists-cdn.assetnote.io/data/kiterunner/swagger-wordlist.txt" | unew -el -t -q wordlists/swagger-wordlist.txt
    curl -s "https://raw.githubusercontent.com/rix4uni/WordList/refs/heads/main/technologies/swagger-ui/swagger-ui.txt" | unew -el -t -q wordlists/swagger-wordlist.txt
    curl -s "https://wordlists-cdn.assetnote.io/data/manual/asp_lowercase.txt" | unew -el -t -q wordlists/asp_lowercase.txt
    curl -s "https://wordlists-cdn.assetnote.io/data/manual/aspx_lowercase.txt" | unew -el -t -q wordlists/aspx_lowercase.txt
    curl -s "https://wordlists-cdn.assetnote.io/data/manual/bak.txt" | unew -el -t -q wordlists/bak.txt
    curl -s "https://wordlists-cdn.assetnote.io/data/manual/do.txt" | unew -el -t -q wordlists/do.txt
    curl -s "https://wordlists-cdn.assetnote.io/data/manual/jsp.txt" | unew -el -t -q wordlists/jsp.txt
    curl -s "https://wordlists-cdn.assetnote.io/data/manual/php.txt" | unew -el -t -q wordlists/php.txt
    curl -s "https://wordlists-cdn.assetnote.io/data/manual/phpmillion.txt" | unew -el -t -q wordlists/phpmillion.txt
    curl -s "https://wordlists-cdn.assetnote.io/data/manual/pl.txt" | unew -el -t -q wordlists/pl.txt
    curl -s "https://wordlists-cdn.assetnote.io/data/manual/xml_filenames.txt" | unew -el -t -q wordlists/xml_filenames.txt
    curl -s "https://raw.githubusercontent.com/rix4uni/resolvers/refs/heads/main/resolvers.txt" | unew -el -t -q wordlists/resolvers.txt
    curl -s "https://raw.githubusercontent.com/trickest/resolvers/refs/heads/main/resolvers-trusted.txt" | unew -el -t -q wordlists/resolvers-trusted.txt
    curl -s "https://raw.githubusercontent.com/six2dez/OneListForAll/refs/heads/main/onelistforallshort.txt" | unew -el -t -q wordlists/onelistforallshort.txt
    curl -s "https://raw.githubusercontent.com/six2dez/OneListForAll/refs/heads/main/onelistforallmicro.txt" | unew -el -t -q wordlists/onelistforallmicro.txt
    curl -s "https://gist.github.com/six2dez/ffc2b14d283e8f8eff6ac83e20a3c4b4/raw" | unew -el -t -q wordlists/perms.txt
    curl -s "https://raw.githubusercontent.com/dwyl/english-words/refs/heads/master/words.txt" | unew -el -t -q wordlists/words.txt
    curl -s "https://raw.githubusercontent.com/dwyl/english-words/refs/heads/master/words_alpha.txt" | unew -el -t -q wordlists/words_alpha.txt
    curl -s "https://raw.githubusercontent.com/rix4uni/ftpx/refs/heads/main/wordlists/ftp-username-password.txt" | unew -el -t -q wordlists/ftp-username-password.txt
    curl -s "https://raw.githubusercontent.com/rix4uni/ftpx/refs/heads/main/wordlists/ftp-password.txt" | unew -el -t -q wordlists/ftp-password.txt
    curl -s "https://raw.githubusercontent.com/cujanovic/Virtual-host-wordlist/refs/heads/master/virtual-host-wordlist.txt" | unew -el -t -q wordlists/virtual-host-wordlist.txt
    curl -s "https://raw.githubusercontent.com/rix4uni/WordList/refs/heads/main/payloads/xss/xss-small.txt" | unew -el -t -q wordlists/xss-small.txt
    curl -s "https://raw.githubusercontent.com/rix4uni/WordList/refs/heads/main/payloads/xss/xss-medium.txt" | unew -el -t -q wordlists/xss-medium.txt
    curl -s "https://raw.githubusercontent.com/rix4uni/WordList/refs/heads/main/payloads/xss/xss-large.txt" | unew -el -t -q wordlists/xss-large.txt
    curl -s "https://raw.githubusercontent.com/rix4uni/WordList/refs/heads/main/payloads/lfi/lfi-small.txt" | unew -el -t -q wordlists/lfi-small.txt
    curl -s "https://raw.githubusercontent.com/rix4uni/WordList/refs/heads/main/payloads/lfi/lfi-medium.txt" | unew -el -t -q wordlists/lfi-medium.txt
    curl -s "https://raw.githubusercontent.com/rix4uni/WordList/refs/heads/main/payloads/lfi/lfi-large.txt" | unew -el -t -q wordlists/lfi-large.txt


    rm -rf wordlists/top-subdomain-list
    git clone https://github.com/jeancarlor/top-subdomain-list.git --depth 1 wordlists/top-subdomain-list &>/dev/null
    cat wordlists/top-subdomain-list/*.txt | unew -el -t -q wordlists/all_hostnames.txt
    rm -rf wordlists/top-subdomain-list

    rm -rf wordlists/n0kovo_subdomains
    git clone https://github.com/n0kovo/n0kovo_subdomains.git --depth 1 wordlists/n0kovo_subdomains &>/dev/null
    mv wordlists/n0kovo_subdomains/*.txt wordlists
    rm -rf wordlists/n0kovo_subdomains

    STOP_SPINNER
    echo -e "${BGREEN}[+] WORDLISTS - INSTALLED${RESET}: ${TIME} seconds"
}


# Install only those tools that used in smallscope
SMALLSCOPE(){
    HTTPX
    NUCLEI
}

# Install only those tools that used in mediumscope
MEDIUMSCOPE(){
    HTTPX
    NUCLEI
}

# Install only those tools that used in largescope
LARGESCOPE(){
    HTTPX
    NUCLEI
}

# Install only those tools that used in cronjobs
CRONJOBS(){
    HTTPX
    NUCLEI
}

# Install all tools that releted to smallscope, mediumscope, largescope, cronjobs
ALL(){
    VARIABLES
    PACKAGES
    PYTHON3
    PYTHON3_PIP
    SETUPTOOLS
    GCC
    GIT
    PIPREQS
    SSHPASS
    CURL
    WGET
    ZIP
    XSEL
    JQ
    YQ
    LIBPCAP_DEV
    NPM
    CSV2JSON
    CSVTK
    PKG_CONFIG
    LIBUDEV_DEV
    BUILD_ESSENTIAL
    CHROMIUM
    CHROME
    PIPX
    CMAKE
    RUST
    PDFTOTEXT
    PARALLEL
    CEWL
    PROXYCHAINS_SETUP
    GO
    GOCL
    SHODAN
    ARJUN
    TLDINFO
    SUBWIZ
    URO
    X8
    FINDOMAIN
    BBOT
    WAYMORE
    XNLINKFINDER
    FEROXBUSTER
    ALTDNS
    MASSCAN
    MASSDNS
    RUSTSCAN
    GHAURI
    # SQLMAP
    INTERLACE
    HTTPX
    XSUBFIND3R
    JSUBFINDER
    NUCLEI
    NUCLEI_TEMPLATE
    SUBFINDER
    CVEMAP
    KATANA
    NAABU
    NMAP
    MAPCIDR
    SHUFFLEDNS
    UNCOVER
    ASNMAP
    CDNCHECK
    DNSX
    CHAOS
    TLDFINDER
    ALTERX
    TLSX
    INTERACTSH_CLIENT
    NOTIFY
    HTTPROBE
    ASSETFINDER
    WAYBACKURLS
    FFF
    MEG
    ANEW
    GRON
    UNFURL
    GF
    GF_PATTERNS
    QSREPLACE
    SUBDOG
    HAKTRAILSFREE
    ORG2ASN
    WHOXYSUBS
    UDON
    TECHX
    UNEW
    UNEWFLUSH
    IP2ORG
    CERTINFO
    XSSCHECKER
    PORTMAP
    PARAMFINDER
    GXSS
    MSARJUN
    HAKRAWLER
    HAKREVDNS
    HAKLISTGEN
    HAKORIGINFINDER
    HAKCHECKURL
    HAKTRAILS
    HAKIP2HOST
    FFUF
    DIRSEARCH
    GOWITNESS
    GITHUB_SUBDOMAINS
    AMASS
    SHOSUBGO
    GAU
    SUBJS
    GOSPIDER
    JAELES
    GETJS
    JSLUICE
    SHORTSCAN
    GUNGNIR
    SNS
    PUREDNS
    DMUT
    GOBUSTER
    SMAP
    DALFOX
    CERO
    GOTATOR
    ANALYTICSRELATIONSHIPS
    MANTRA
    CRT
    URLGRAB
    GOLINKFINDER
    LINX
    KXSS
    GALER
    JSFINDER
    PATHFINDER
    TRUFFLEHOG
    JSHUNTER
    PPFUZZ
    BRUTESPRAY
    LINKINSPECTOR
    WORDGEN
    FUZZULI
    PYXSS
    ARINRANGE
    BUILTWITHSUBS
    GOOP
    COMMIX
    PVREPLACE
    SSB
    FTPX
    DNSTAKE
    MX_TAKEOVER
    SUBZY
    URLDEDUPE
    TIMELIMITX
    SOURCEMAPPER
    JSCRAWLER
    GORKER
    ROBOTXT
    ROBOXTRACTOR
    PATHCRAWLER
    CRAWLEY
    XCRAWL3R
    XURLFIND3R
    GITHUB_ENDPOINTS
    URLFINDER
    CARIDDI
    UFORALL
    EMAILFINDER
    FAVIRECON
    FAVINFO
    DLEVEL
    SUBDOMAINFUZZ
    GOURLEX
    CSPFINDER
    CSPRECON
    GITREPOENUM
    S3SCANNER
    SPK
    RIPGEN
    GOALTDNS
    DNSGEN
    RCERT
    IPFINDER
    CONFIGS
    TRICKESTCLOUD
    WORDLISTS
}


# Dynamically call the selected function
$FUNC

# https://github.com/Screetsec/Sudomy

# git clone https://github.com/GerbenJavado/LinkFinder.git --depth 1 && cd LinkFinder && pip3 install -r requirements.txt && cd .. && mv LinkFinder ~/bin && echo "alias linkfinder='python3 ~/bin/LinkFinder/linkfinder.py'" >> ~/.bashrc && source ~/.bashrc

# git clone https://github.com/shmilylty/OneForAll.git --depth 1 && cd OneForAll && python3 -m pip install -U pip setuptools wheel && pip3 install -r requirements.txt && cd .. && mv OneForAll ~/bin && source ~/.bashrc

# git clone https://github.com/m4ll0k/SecretFinder.git && cd SecretFinder && python3 -m pip install -r requirements.txt && cd .. && mv SecretFinder ~/bin
